# Generated by Django 4.1.13 on 2025-09-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bairro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_bairro", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "Bairros",
            },
        ),
    ]
