# Generated by Django 4.1.13 on 2026-03-15 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0009_empresa_senha_portal"),
        ("estados", "0003_alter_estado_vinc_emp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estado",
            name="nome_estado",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="estado",
            name="vinc_emp",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="empresas.empresa",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="estado",
            constraint=models.UniqueConstraint(
                fields=("nome_estado", "vinc_emp"),
                name="unique_nome_estado_por_empresa",
            ),
        ),
    ]
