# Generated by Django 4.1.13 on 2026-05-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estados', '0004_alter_estado_nome_estado_alter_estado_vinc_emp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='estado',
            constraint=models.UniqueConstraint(fields=('codigo', 'vinc_emp'), name='unique_codigo_estado_empresa'),
        ),
    ]
