# Generated by Django 4.1.13 on 2026-07-15 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(blank=True, null=True)),
                ('descricao', models.CharField(max_length=100)),
                ('vinc_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Cobrança',
            },
        ),
        migrations.AddConstraint(
            model_name='tipocobranca',
            constraint=models.UniqueConstraint(fields=('descricao', 'vinc_emp'), name='unique_tipo_cobranca_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='tipocobranca',
            constraint=models.UniqueConstraint(fields=('codigo', 'vinc_emp'), name='unique_codigo_tipo_empresa'),
        ),
    ]
