# Generated by Django 4.1.13 on 2025-09-27 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("filiais", "0005_remove_filial_qtd_filial_remove_filial_qtd_usuarios"),
        ("tipo_cobranca", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipocobranca",
            name="vinc_emp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="filiais.filial",
            ),
        ),
    ]
