# Generated by Django 4.1.13 on 2026-07-15 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(blank=True, null=True)),
                ('descricao', models.CharField(max_length=100)),
                ('margem', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tipo', models.CharField(choices=[('A vista', 'A vista'), ('A prazo', 'A prazo')], default='A vista', max_length=8, verbose_name='Tipo de Plano')),
                ('vinc_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
            options={
                'verbose_name_plural': 'Tabelas de Preço',
            },
        ),
        migrations.AddConstraint(
            model_name='tabelapreco',
            constraint=models.UniqueConstraint(fields=('descricao', 'vinc_emp'), name='unique_descricao_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='tabelapreco',
            constraint=models.UniqueConstraint(fields=('codigo', 'vinc_emp'), name='unique_codigo_tabela_empresa'),
        ),
    ]
