# Generated by Django 4.1.13 on 2025-11-01 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("filiais", "0005_remove_filial_qtd_filial_remove_filial_qtd_usuarios"),
    ]

    operations = [
        migrations.CreateModel(
            name="TabelaPreco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=100, unique=True)),
                ("margem", models.CharField(max_length=100, unique=True)),
                (
                    "vinc_emp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="filiais.filial",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tabelas de Preço",
            },
        ),
    ]
