# Generated by Django 4.1.13 on 2025-11-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabelas_preco", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tabelapreco",
            name="margem",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
