# Generated by Django 4.1.13 on 2025-11-23 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0004_alter_empresa_principal"),
        ("tabelas_preco", "0002_alter_tabelapreco_margem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tabelapreco",
            name="vinc_emp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="empresas.empresa",
            ),
        ),
    ]
