# Generated by Django 4.1.13 on 2026-02-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabelas_preco", "0003_alter_tabelapreco_vinc_emp"),
    ]

    operations = [
        migrations.AddField(
            model_name="tabelapreco",
            name="tipo",
            field=models.CharField(
                choices=[("A vista", "A vista"), ("A prazo", "A prazo")],
                default="A prazo",
                max_length=8,
                verbose_name="Tipo de Plano",
            ),
        ),
    ]
