# Generated by Django 4.1.13 on 2026-03-20 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0009_empresa_senha_portal"),
        ("tabelas_preco", "0004_tabelapreco_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tabelapreco",
            name="descricao",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="tabelapreco",
            name="vinc_emp",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="empresas.empresa",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="tabelapreco",
            constraint=models.UniqueConstraint(
                fields=("descricao", "vinc_emp"), name="unique_descricao_por_empresa"
            ),
        ),
    ]
