# Generated by Django 4.1.13 on 2026-05-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelas_preco', '0005_alter_tabelapreco_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelapreco',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
