# Generated by Django 4.1.13 on 2026-06-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabelas_preco", "0007_tabelapreco_unique_codigo_tabela_empresa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tabelapreco",
            name="tipo",
            field=models.CharField(
                choices=[("A vista", "A vista"), ("A prazo", "A prazo")],
                default="A vista",
                max_length=8,
                verbose_name="Tipo de Plano",
            ),
        ),
    ]
