# Generated by Django 4.1.13 on 2026-05-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0004_alter_unidade_nome_unidade_alter_unidade_vinc_emp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
