# Generated by Django 4.1.13 on 2026-05-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0005_unidade_codigo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='unidade',
            constraint=models.UniqueConstraint(fields=('codigo', 'vinc_emp'), name='unique_codigo_unidade_empresa'),
        ),
    ]
