# Generated by Django 4.1.13 on 2025-09-25 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("unidades", "__first__"),
        ("grupos", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[("Ativo", "Ativo"), ("Inativo", "Inativo")],
                        default="Ativo",
                        max_length=50,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "tp_prod",
                    models.CharField(
                        choices=[
                            ("Principal", "Principal"),
                            ("Adicional", "Adicional"),
                        ],
                        max_length=50,
                        verbose_name="Tipo do Produto",
                    ),
                ),
                (
                    "lista_orc",
                    models.BooleanField(
                        default=False, verbose_name="Exibir na Lista (Orçamentos)"
                    ),
                ),
                ("desc_prod", models.CharField(max_length=50)),
                (
                    "desc_normalizado",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("vl_compra", models.CharField(default="0.00", max_length=50)),
                ("vl_prod", models.CharField(max_length=50)),
                ("estoque_prod", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "grupo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="grupos.grupo",
                    ),
                ),
                (
                    "unidProd",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="unidades.unidade",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Produtos",
            },
        ),
    ]
