# Generated by Django 4.1.13 on 2026-07-15 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0001_initial'),
        ('empresas', '0001_initial'),
        ('tabelas_preco', '0001_initial'),
        ('unidades', '0001_initial'),
        ('grupos', '0001_initial'),
        ('marcas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=50, verbose_name='Situação')),
                ('tp_prod', models.CharField(blank=True, choices=[('Principal', 'Principal'), ('Adicional', 'Adicional')], max_length=50, null=True, verbose_name='Tipo do Produto')),
                ('lista_orc', models.BooleanField(default=False, verbose_name='Exibir na Lista (Orçamentos)')),
                ('desc_prod', models.CharField(max_length=50, verbose_name='Descrição')),
                ('desc_normalizado', models.CharField(blank=True, max_length=255, null=True)),
                ('vl_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estoque_prod', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estoque_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estoque_maximo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('especifico', models.CharField(blank=True, choices=[('', ''), ('Portinhola', 'Portinhola'), ('Alçapão', 'Alçapão'), ('Coluna Removível', 'Coluna Removível'), ('Serviço/Transporte', 'Serviço/Transporte')], default='', max_length=50, null=True, verbose_name='Produto Específico')),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grupos.grupo')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marcas.marca')),
                ('unidProd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidades.unidade')),
                ('vinc_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
            options={
                'verbose_name_plural': 'Produtos',
                'permissions': [('clonar_produto', 'Pode clonar produtos'), ('relatorio_vendas_produto', 'Pode acessar relatório de vendas de pedidos.')],
            },
        ),
        migrations.CreateModel(
            name='ProdutoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_fornecedor', models.CharField(blank=True, default='', max_length=60)),
                ('descricao_fornecedor', models.CharField(blank=True, max_length=255, null=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_fornecedor', to='fornecedores.fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores_vinculados', to='produtos.produto')),
                ('vinc_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='CodigoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos', to='produtos.produto')),
                ('vinc_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ESTOQUE', 'Estoque'), ('CONTA_RECEBER', 'Conta a Receber'), ('CONTA_PAGAR', 'Conta a Pagar'), ('LICENCA', 'Licença'), ('CERTIFICADO', 'Certificado Digital'), ('NFE', 'NF-e'), ('BACKUP', 'Backup')], max_length=30)),
                ('referencia', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('status', models.CharField(default='Aberto', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoTabela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vl_prod', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelas_preco.tabelapreco')),
            ],
            options={
                'verbose_name': 'Tabela de preço por produto',
                'verbose_name_plural': 'Tabelas de preço por produto',
                'unique_together': {('produto', 'tabela')},
            },
        ),
        migrations.AddConstraint(
            model_name='produtofornecedor',
            constraint=models.UniqueConstraint(fields=('vinc_emp', 'fornecedor', 'codigo_fornecedor'), name='unique_codigo_fornecedor_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(fields=('codigo', 'vinc_emp'), name='unique_codigo_produto_empresa'),
        ),
        migrations.AddConstraint(
            model_name='codigoproduto',
            constraint=models.UniqueConstraint(fields=('vinc_emp', 'codigo'), name='unique_codigo_por_empresa'),
        ),
    ]
