# Generated by Django 4.1.13 on 2026-07-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='diametro_eixo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Diâmetro do eixo em cm. Preencher apenas para produtos do tipo Eixo.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='especifico',
            field=models.CharField(blank=True, choices=[('', ''), ('Portinhola', 'Portinhola'), ('Alçapão', 'Alçapão'), ('Coluna Removível', 'Coluna Removível'), ('Serviço/Transporte', 'Serviço/Transporte'), ('Eixo', 'Eixo')], default='', max_length=50, null=True, verbose_name='Produto Específico'),
        ),
    ]
