# Generated by Django 4.1.13 on 2025-09-27 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0002_produto_vinc_emp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="produto",
            options={
                "permissions": [("clonar_produto", "Pode clonar produtos")],
                "verbose_name_plural": "Produtos",
            },
        ),
    ]
