# Generated by Django 4.1.13 on 2026-07-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_diametro_eixo_alter_produto_especifico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('ESTOQUE_MINIMO', 'Estoque Mínimo'), ('ESTOQUE_MAXIMO', 'Estoque Máximo'), ('CONTA_RECEBER', 'Conta a Receber'), ('CONTA_PAGAR', 'Conta a Pagar'), ('LICENCA', 'Licença'), ('CERTIFICADO', 'Certificado Digital'), ('NFE', 'NF-e'), ('BACKUP', 'Backup')], max_length=30),
        ),
    ]
