# Generated by Django 4.1.13 on 2026-07-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_alerta_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='espessura_lam',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Espessura da lâmina em cm. Preencher apenas para produtos do tipo Lâmina.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='especifico',
            field=models.CharField(blank=True, choices=[('', ''), ('Portinhola', 'Portinhola'), ('Alçapão', 'Alçapão'), ('Coluna Removível', 'Coluna Removível'), ('Serviço/Transporte', 'Serviço/Transporte'), ('Eixo', 'Eixo'), ('Lâmina', 'Lâmina')], default='', max_length=50, null=True, verbose_name='Produto Específico'),
        ),
    ]
