# Generated by Django 4.1.13 on 2025-11-01 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("marcas", "0001_initial"),
        ("produtos", "0003_alter_produto_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="marca",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="marcas.marca",
            ),
        ),
    ]
