# Generated by Django 4.1.13 on 2025-11-01 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tabelas_preco", "0002_alter_tabelapreco_margem"),
        ("produtos", "0004_produto_marca"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="margem",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produto",
            name="tabela",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tabelas_preco.tabelapreco",
            ),
        ),
    ]
