# Generated by Django 4.1.13 on 2026-07-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produto_espessura_lam_alter_produto_especifico'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='peso_m2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso (Kg) por M². Preencher apenas para produtos do tipo Lâmina.', max_digits=6, null=True),
        ),
    ]
