# Generated by Django 4.1.13 on 2025-11-02 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tabelas_preco", "0002_alter_tabelapreco_margem"),
        ("produtos", "0005_produto_margem_produto_tabela"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="margem",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="tabela",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="vl_prod",
        ),
        migrations.CreateModel(
            name="ProdutoTabela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vl_prod", models.DecimalField(decimal_places=2, max_digits=10)),
                ("margem", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produtos.produto",
                    ),
                ),
                (
                    "tabela",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tabelas_preco.tabelapreco",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tabela de preço por produto",
                "verbose_name_plural": "Tabelas de preço por produto",
                "unique_together": {("produto", "tabela")},
            },
        ),
    ]
