# Generated by Django 4.1.13 on 2025-11-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0006_remove_produto_margem_remove_produto_tabela_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="estoque_prod",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
