# Generated by Django 4.1.13 on 2025-11-13 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0007_alter_produto_estoque_prod"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodigoProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codigos",
                        to="produtos.produto",
                    ),
                ),
            ],
        ),
    ]
