# Generated by Django 4.1.13 on 2026-01-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_alter_produto_vinc_emp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('QTD', 'Quantidade'), ('SELECAO', 'Seleção')], max_length=20)),
                ('expressao', models.TextField()),
            ],
        ),
    ]
