# Generated by Django 4.1.13 on 2026-01-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_regraproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='regraproduto',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='regraproduto',
            name='descricao',
            field=models.CharField(default='', help_text='Descrição legível da regra', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='regraproduto',
            name='codigo',
            field=models.CharField(help_text='Identificador interno da regra (ex: MOTOR, LAMINA, PINTURA)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='regraproduto',
            name='expressao',
            field=models.TextField(help_text='Fórmula ou regra (ex: m2, alt_c * 4, JSON para seleção)'),
        ),
        migrations.AlterField(
            model_name='regraproduto',
            name='tipo',
            field=models.CharField(choices=[('QTD', 'Cálculo de Quantidade'), ('SELECAO', 'Seleção Automática')], max_length=20),
        ),
    ]
