# Generated by Django 4.1.13 on 2026-01-07 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_regraproduto_ativo_regraproduto_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='regra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.regraproduto'),
        ),
    ]
