# Generated by Django 4.1.13 on 2026-01-07 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_alter_empresa_principal'),
        ('produtos', '0012_produto_regra'),
    ]

    operations = [
        migrations.AddField(
            model_name='regraproduto',
            name='vinc_emp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
            preserve_default=False,
        ),
    ]
