# Generated by Django 4.1.13 on 2026-01-07 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0013_regraproduto_vinc_emp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regraproduto',
            name='vinc_emp',
        ),
    ]
