# Generated by Django 4.1.13 on 2026-01-07 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0014_remove_regraproduto_vinc_emp'),
        ('regras_produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='regra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regras_produto.regraproduto'),
        ),
        migrations.DeleteModel(
            name='RegraProduto',
        ),
    ]
