# Generated by Django 4.1.13 on 2026-03-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0015_alter_produto_regra_delete_regraproduto"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="especifico",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("Portinhola", "Portinhola"),
                    ("Alçapão", "Alçapão"),
                    ("Coluna Removível", "Coluna Removível"),
                    ("Serviço/Transporte", "Serviço/Transporte"),
                ],
                default="",
                max_length=50,
                verbose_name="Produto Específico",
            ),
        ),
    ]
