# Generated by Django 4.1.13 on 2026-03-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0016_produto_especifico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="vl_compra",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
