# Generated by Django 4.1.13 on 2026-03-15 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0009_empresa_senha_portal"),
        ("produtos", "0017_alter_produto_vl_compra"),
    ]

    operations = [
        migrations.AddField(
            model_name="codigoproduto",
            name="vinc_emp",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="empresas.empresa",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="codigoproduto",
            name="codigo",
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name="codigoproduto",
            constraint=models.UniqueConstraint(
                fields=("vinc_emp", "codigo"), name="unique_codigo_por_empresa"
            ),
        ),
    ]
