# Generated by Django 4.1.13 on 2026-03-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0018_codigoproduto_vinc_emp_alter_codigoproduto_codigo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="especifico",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("Portinhola", "Portinhola"),
                    ("Alçapão", "Alçapão"),
                    ("Coluna Removível", "Coluna Removível"),
                    ("Serviço/Transporte", "Serviço/Transporte"),
                ],
                default="",
                max_length=50,
                null=True,
                verbose_name="Produto Específico",
            ),
        ),
    ]
