# Generated by Django 4.1.13 on 2026-03-21 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fornecedores", "0004_alter_fornecedor_dt_reg"),
        ("empresas", "0009_empresa_senha_portal"),
        ("produtos", "0019_alter_produto_especifico"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProdutoFornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_fornecedor",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "descricao_fornecedor",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produtos_fornecedor",
                        to="fornecedores.fornecedor",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produtos.produto",
                    ),
                ),
                (
                    "vinc_emp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.empresa",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="produtofornecedor",
            constraint=models.UniqueConstraint(
                fields=("vinc_emp", "fornecedor", "codigo_fornecedor"),
                name="unique_codigo_fornecedor_por_empresa",
            ),
        ),
    ]
