# Generated by Django 4.1.13 on 2026-03-21 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0020_produtofornecedor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtofornecedor",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fornecedores_vinculados",
                to="produtos.produto",
            ),
        ),
    ]
