# Generated by Django 4.1.13 on 2026-04-10 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0021_alter_produtofornecedor_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='regra',
        ),
    ]
