# Generated by Django 4.1.13 on 2026-04-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0022_remove_produto_regra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tp_prod',
            field=models.CharField(blank=True, choices=[('Principal', 'Principal'), ('Adicional', 'Adicional')], max_length=50, null=True, verbose_name='Tipo do Produto'),
        ),
    ]
