# Generated by Django 4.1.13 on 2026-05-14 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0023_alter_produto_tp_prod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'permissions': [('clonar_produto', 'Pode clonar produtos'), ('relatorio_vendas_produto', 'Pode acessar relatório de vendas de pedidos.')], 'verbose_name_plural': 'Produtos'},
        ),
    ]
