# Generated by Django 4.1.13 on 2026-05-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0024_alter_produto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
