# Generated by Django 4.1.13 on 2026-04-19 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bairros", "0004_alter_bairro_nome_bairro_alter_bairro_vinc_emp_and_more"),
        ("estados", "0004_alter_estado_nome_estado_alter_estado_vinc_emp_and_more"),
        ("cidades", "0004_alter_cidade_nome_cidade_alter_cidade_vinc_emp_and_more"),
        ("empresas", "0009_empresa_senha_portal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[("Ativo", "Ativo"), ("Inativo", "Inativo")],
                        max_length=10,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "pessoa",
                    models.CharField(
                        choices=[("Física", "Física"), ("Jurídica", "Jurídica")],
                        max_length=10,
                        verbose_name="Pessoa",
                    ),
                ),
                ("cpf_cnpj", models.CharField(max_length=25)),
                ("ie", models.CharField(blank=True, max_length=20, null=True)),
                ("razao_social", models.CharField(max_length=100)),
                ("fantasia", models.CharField(max_length=100)),
                ("endereco", models.CharField(max_length=100)),
                ("cep", models.CharField(max_length=10)),
                ("numero", models.CharField(max_length=10)),
                ("complem", models.CharField(blank=True, default="", max_length=30)),
                ("tel", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=40)),
                (
                    "dt_reg",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Data de Registro",
                    ),
                ),
                (
                    "bairro",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bairros.bairro",
                    ),
                ),
                (
                    "cidade",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cidades.cidade",
                    ),
                ),
                (
                    "uf",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="estados.estado",
                    ),
                ),
                (
                    "vinc_emp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vendedores",
            },
        ),
    ]
