# Generated by Django 4.1.13 on 2025-09-25 16:29

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filiais.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cidades", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("bairros", "0001_initial"),
        ("estados", "0001_initial"),
        ("bancos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Filial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[("Ativa", "Ativa"), ("Inativa", "Inativa")],
                        max_length=10,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "tp_chave",
                    models.CharField(
                        choices=[
                            ("CPF", "CPF"),
                            ("CNPJ", "CNPJ"),
                            ("E-mail", "E-mail"),
                            ("Telefone", "Telefone"),
                            ("Chave Aleatória", "Chave Aleatória"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Chave Pix",
                    ),
                ),
                (
                    "chave_pix",
                    models.CharField(max_length=100, verbose_name="Chave Pix"),
                ),
                (
                    "beneficiario",
                    models.CharField(max_length=255, verbose_name="Nome Beneficiário"),
                ),
                (
                    "info_comp",
                    models.TextField(blank=True, default="Obrigado pela preferência!"),
                ),
                (
                    "info_orcamento",
                    models.TextField(
                        blank=True,
                        default="*Caro cliente, caso você encontre um orçamento com valor inferior, podemos analisar o orçamento concorrente para fecharmos negócio.",
                    ),
                ),
                ("cnpj", models.CharField(max_length=20, verbose_name="CNPJ")),
                (
                    "ie",
                    models.CharField(max_length=20, verbose_name="Inscrição Estadual"),
                ),
                (
                    "razao_social",
                    models.CharField(max_length=100, verbose_name="Razão Social"),
                ),
                ("fantasia", models.CharField(max_length=100, verbose_name="Fantasia")),
                ("endereco", models.CharField(max_length=100, verbose_name="Endereço")),
                ("cep", models.CharField(max_length=10, verbose_name="CEP")),
                ("numero", models.CharField(max_length=10, verbose_name="Nº")),
                (
                    "complem",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Complemento"
                    ),
                ),
                ("tel", models.CharField(max_length=15, verbose_name="Fone")),
                ("email", models.EmailField(max_length=40, verbose_name="E-mail")),
                (
                    "fantasia_normalizado",
                    models.CharField(editable=False, max_length=255),
                ),
                (
                    "logo",
                    models.FileField(
                        blank=True,
                        default="default_logo.png",
                        null=True,
                        upload_to="logo/",
                    ),
                ),
                (
                    "dt_criacao",
                    models.CharField(
                        default=filiais.models.data_hoje_formatada,
                        max_length=30,
                        verbose_name="Data de Registro",
                    ),
                ),
                (
                    "dt_inativacao",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Data de Inativação",
                    ),
                ),
                (
                    "qtd_filial",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantidade de Filiais Ativas"
                    ),
                ),
                (
                    "qtd_usuarios",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Quantidade de Usuários Ativos"
                    ),
                ),
                (
                    "principal",
                    models.BooleanField(default=False, verbose_name="Filial Principal"),
                ),
                (
                    "bairro",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bairros.bairro",
                    ),
                ),
                (
                    "banco",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bancos.banco",
                    ),
                ),
                (
                    "cidade",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cidades.cidade",
                    ),
                ),
                (
                    "uf",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="estados.estado",
                    ),
                ),
                (
                    "vinculada_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filiais_secundarias",
                        to="filiais.filial",
                        verbose_name="Filial Vinculada à",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Filiais",
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "gerar_senha_lib",
                    models.BooleanField(
                        default=False, verbose_name="Gerar Senha de Liberação"
                    ),
                ),
                (
                    "senha_liberacao",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Senha de Liberação",
                    ),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="filiais.filial",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "unique_together": {("username", "filial")},
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
