# Generated by Django 4.1.13 on 2026-07-15 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        ('tecnicos', '0001_initial'),
        ('bancos', '0001_initial'),
        ('tabelas_preco', '0001_initial'),
        ('vendedores', '0001_initial'),
        ('empresas', '0001_initial'),
        ('filiais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilialContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('site', models.URLField(blank=True, null=True)),
                ('instagram', models.CharField(blank=True, max_length=80, null=True)),
                ('facebook', models.CharField(blank=True, max_length=80, null=True)),
                ('email_financeiro', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_fiscal', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_comercial', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilialEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controla_lote', models.BooleanField(default=False)),
                ('controla_validade', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FilialFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp_chave', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('E-mail', 'E-mail'), ('Telefone', 'Telefone'), ('Chave Aleatória', 'Chave Aleatória')], max_length=20, verbose_name='Tipo de Chave Pix')),
                ('chave_pix', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave Pix')),
                ('beneficiario', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Beneficiário')),
                ('max_parcelas', models.PositiveIntegerField(default=1)),
                ('max_dias_intervalo', models.PositiveIntegerField(default=30)),
                ('tp_calc_juros', models.CharField(choices=[('Percentual', 'Percentual'), ('Valor', 'Valor')], default='Percentual', max_length=15, verbose_name='Tp. Cálculo Juros')),
                ('tp_calc_multa', models.CharField(choices=[('Percentual', 'Percentual'), ('Valor', 'Valor')], default='Percentual', max_length=15, verbose_name='Tp. Cálculo Multa')),
                ('ft_multa', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Fator Multa')),
                ('ft_juros', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Fator Juros')),
                ('desconto_maximo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('acrescimo_maximo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('limite_credito_padrao', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='FilialFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crt', models.CharField(choices=[('1', 'Simples Nacional'), ('2', 'Simples Nacional Excesso'), ('3', 'Regime Normal')], default='1', max_length=5, verbose_name='CRT')),
                ('im', models.CharField(blank=True, max_length=30, null=True, verbose_name='Inscrição Municipal')),
                ('suframa', models.CharField(blank=True, max_length=30, null=True)),
                ('certificado', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('senha_certificado', models.CharField(blank=True, max_length=150, null=True)),
                ('serie_nfe', models.PositiveIntegerField(default=1)),
                ('serie_nfce', models.PositiveIntegerField(default=1)),
                ('ultimo_numero_nfe', models.PositiveIntegerField(default=0)),
                ('ultimo_numero_nfce', models.PositiveIntegerField(default=0)),
                ('ambiente_fiscal', models.CharField(choices=[('Homologação', 'Homologação'), ('Produção', 'Produção')], default='Homologação', max_length=15)),
                ('cnae_principal', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilialImpressao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imprimir_logo', models.BooleanField(default=True)),
                ('imp_recibo_cr', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Auto', 'Auto')], default='Sim', max_length=20, verbose_name='Questionar Imp. de Recibo')),
            ],
        ),
        migrations.CreateModel(
            name='FilialObservacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs_pedido', models.TextField(blank=True, null=True)),
                ('observacao_boleto', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilialOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_contrato', models.CharField(choices=[('Layout 1', 'Layout 1'), ('Layout 2', 'Layout 2')], default='Layout 1', max_length=10, verbose_name='Layout Contrato')),
                ('layout_prod', models.CharField(choices=[('1', 'Layout 1'), ('2', 'Layout 2')], default='1', max_length=10, verbose_name='L. PDF Produção')),
                ('imp_recibo_orc', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Auto', 'Auto')], default='Sim', max_length=20, verbose_name='Questionar Imp. de Recibo')),
                ('info_comp', models.TextField(blank=True, default='Obrigado pela preferência!', null=True)),
                ('info_local', models.TextField(blank=True, default='Atendemos em todo estado do Pará!', null=True)),
                ('info_orcamento', models.TextField(blank=True, default='*Caro cliente, caso você encontre um orçamento com valor inferior, podemos analisar o orçamento concorrente para fecharmos negócio.', null=True)),
                ('mt_qt_lam', models.CharField(blank=True, default='(alt_corte + rolo) / 0.075', max_length=100, null=True, verbose_name='Multip. Qtde. Lâminas')),
                ('multi_m2', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True, verbose_name='Multiplicador M²')),
                ('multi_lg_corte1', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True, verbose_name='Multiplicador Lg. Corte (Fora do Vão)')),
                ('multi_lg_corte2', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True, verbose_name='Multiplicador Lg. Corte (Dentro do Vão)')),
                ('multi_lg_corte3', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True, verbose_name='Multiplicador Lg. Corte (1 Lado do Vão)')),
            ],
        ),
        migrations.CreateModel(
            name='LogUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CRIAR', 'Criou'), ('ALTERAR', 'Alterou'), ('EXCLUIR', 'Excluiu'), ('FATURAR', 'Faturou'), ('CANCELAR', 'Cancelou'), ('BAIXA', 'Baixa Financeira'), ('ESTORNO', 'Estorno'), ('ABERTURA', 'Abriu Caixa'), ('FECHAMENTO', 'Fechou Caixa'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('OUTRO', 'Outro')], max_length=20)),
                ('modulo', models.CharField(max_length=50)),
                ('objeto', models.CharField(max_length=200)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('descricao', models.TextField()),
                ('alteracoes', models.JSONField(blank=True, null=True, verbose_name='Alterações')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.RenameField(
            model_name='filial',
            old_name='bairro',
            new_name='bairro_fil',
        ),
        migrations.RenameField(
            model_name='filial',
            old_name='cidade',
            new_name='cidade_fil',
        ),
        migrations.AlterUniqueTogether(
            name='usuario',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='filial',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='qtd_filial',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='qtd_usuarios',
        ),
        migrations.AddField(
            model_name='filial',
            name='agrupa_itens',
            field=models.BooleanField(default=True, verbose_name='Agrupar itens no pedido'),
        ),
        migrations.AddField(
            model_name='filial',
            name='banco_fil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bancos.banco'),
        ),
        migrations.AddField(
            model_name='filial',
            name='cli',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='filial',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filial',
            name='ft_juros',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Fator Juros'),
        ),
        migrations.AddField(
            model_name='filial',
            name='ft_multa',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Fator Multa'),
        ),
        migrations.AddField(
            model_name='filial',
            name='imp_recibo_cr',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Auto', 'Auto')], default='Sim', max_length=20, verbose_name='Questionar Imp. de Recibo'),
        ),
        migrations.AddField(
            model_name='filial',
            name='imp_recibo_orc',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Auto', 'Auto')], default='Sim', max_length=20, verbose_name='Questionar Imp. de Recibo'),
        ),
        migrations.AddField(
            model_name='filial',
            name='info_local',
            field=models.TextField(blank=True, default='Atendemos em todo estado do Pará!', null=True),
        ),
        migrations.AddField(
            model_name='filial',
            name='layout_contrato',
            field=models.CharField(choices=[('Layout 1', 'Layout 1'), ('Layout 2', 'Layout 2')], default='Layout 1', max_length=10, verbose_name='Layout Contrato'),
        ),
        migrations.AddField(
            model_name='filial',
            name='layout_prod',
            field=models.CharField(choices=[('1', 'Layout 1'), ('2', 'Layout 2')], default='1', max_length=10, verbose_name='L. PDF Produção'),
        ),
        migrations.AddField(
            model_name='filial',
            name='max_dias_intervalo',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='filial',
            name='max_parcelas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='filial',
            name='mt_qt_lam',
            field=models.CharField(blank=True, default='(alt_corte + rolo) / 0.075', max_length=100, null=True, verbose_name='Multip. Qtde. Lâminas'),
        ),
        migrations.AddField(
            model_name='filial',
            name='multi_lg_corte1',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True, verbose_name='Multiplicador Lg. Corte (Fora do Vão)'),
        ),
        migrations.AddField(
            model_name='filial',
            name='multi_lg_corte2',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True, verbose_name='Multiplicador Lg. Corte (Dentro do Vão)'),
        ),
        migrations.AddField(
            model_name='filial',
            name='multi_lg_corte3',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True, verbose_name='Multiplicador Lg. Corte (1 Lado do Vão)'),
        ),
        migrations.AddField(
            model_name='filial',
            name='multi_m2',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True, verbose_name='Multiplicador M²'),
        ),
        migrations.AddField(
            model_name='filial',
            name='tb_preco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tabelas_preco.tabelapreco'),
        ),
        migrations.AddField(
            model_name='filial',
            name='tec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tecnicos.tecnico'),
        ),
        migrations.AddField(
            model_name='filial',
            name='tp_calc_juros',
            field=models.CharField(choices=[('Percentual', 'Percentual'), ('Valor', 'Valor')], default='Percentual', max_length=15, verbose_name='Tp. Cálculo Juros'),
        ),
        migrations.AddField(
            model_name='filial',
            name='tp_calc_multa',
            field=models.CharField(choices=[('Percentual', 'Percentual'), ('Valor', 'Valor')], default='Percentual', max_length=15, verbose_name='Tp. Cálculo Multa'),
        ),
        migrations.AddField(
            model_name='filial',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendedores.vendedor'),
        ),
        migrations.AddField(
            model_name='filial',
            name='vinc_emp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo_local',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='filial_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='filiais.filial'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='receber_alerta_estoque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_caracteristicas_orcamentos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_conv_orc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_cores_orcamentos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_evolucao_orcamentos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_faturamento_diario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_formas_orcamentos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_m2_total',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_peso_total',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_ranking_clientes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_ranking_tecnicos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_res_orc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_res_orc_tec',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_situacao_orcamentos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_situacao_valor_orcamentos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_status_orcamentos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_tempo_medio_faturamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_ticket_medio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_top_10_produtos_qtde',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_top_10_produtos_vl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_valor_perdido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_vl_total_faturado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='filial',
            name='beneficiario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Beneficiário'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave Pix'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='dt_criacao',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Data de Registro'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='dt_inativacao',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Data de Inativação'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='email',
            field=models.EmailField(blank=True, max_length=40, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='ie',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='info_comp',
            field=models.TextField(blank=True, default='Obrigado pela preferência!', null=True),
        ),
        migrations.AlterField(
            model_name='filial',
            name='info_orcamento',
            field=models.TextField(blank=True, default='*Caro cliente, caso você encontre um orçamento com valor inferior, podemos analisar o orçamento concorrente para fecharmos negócio.', null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha_liberacao',
            field=models.CharField(blank=True, help_text='Para nova senha, preencha esse campo!', max_length=20, null=True, verbose_name='Senha de Liberação'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='usuario',
            unique_together={('username', 'empresa')},
        ),
        migrations.AddConstraint(
            model_name='filial',
            constraint=models.UniqueConstraint(fields=('codigo', 'vinc_emp'), name='unique_codigo_filial_empresa'),
        ),
        migrations.AddField(
            model_name='logusuario',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='logusuario',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filiais.filial'),
        ),
        migrations.AddField(
            model_name='logusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filialorcamento',
            name='filial',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orcamento_porta', to='filiais.filial'),
        ),
        migrations.AddField(
            model_name='filialobservacao',
            name='filial',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='observacoes', to='filiais.filial'),
        ),
        migrations.AddField(
            model_name='filialimpressao',
            name='filial',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impressao', to='filiais.filial'),
        ),
        migrations.AddField(
            model_name='filialfiscal',
            name='filial',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal', to='filiais.filial'),
        ),
        migrations.AddField(
            model_name='filialfinanceiro',
            name='banco_fil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bancos.banco'),
        ),
        migrations.AddField(
            model_name='filialfinanceiro',
            name='filial',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financeiro', to='filiais.filial'),
        ),
        migrations.AddField(
            model_name='filialestoque',
            name='filial',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='filiais.filial'),
        ),
        migrations.AddField(
            model_name='filialcontato',
            name='filial',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contato', to='filiais.filial'),
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='filial',
        ),
    ]
