# Generated by Django 4.1.13 on 2025-09-25 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0001_initial"),
        ("filiais", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filial",
            old_name="bairro",
            new_name="bairro_fil",
        ),
        migrations.RenameField(
            model_name="filial",
            old_name="banco",
            new_name="banco_fil",
        ),
        migrations.RenameField(
            model_name="filial",
            old_name="cidade",
            new_name="cidade_fil",
        ),
        migrations.AddField(
            model_name="filial",
            name="vinc_emp",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="empresas.empresa",
            ),
            preserve_default=False,
        ),
    ]
