# Generated by Django 4.1.13 on 2025-09-26 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0001_initial"),
        ("filiais", "0002_rename_bairro_filial_bairro_fil_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usuario",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="usuario",
            name="codigo_local",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usuarios",
                to="empresas.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="filial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios",
                to="filiais.filial",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usuario",
            unique_together={("username", "empresa")},
        ),
    ]
