# Generated by Django 4.1.13 on 2025-09-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiais", "0003_alter_usuario_unique_together_usuario_codigo_local_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="is_master",
            field=models.BooleanField(default=False),
        ),
    ]
