# Generated by Django 4.1.13 on 2026-07-15 22:26

from django.db import migrations, models
import filiais.models


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0003_alter_usuario_senha_liberacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='logo',
            field=models.FileField(blank=True, default='default_logo.png', null=True, upload_to=filiais.models.caminho_logo_filial),
        ),
    ]
