# Generated by Django 4.1.13 on 2025-09-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("filiais", "0004_usuario_is_master"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filial",
            name="qtd_filial",
        ),
        migrations.RemoveField(
            model_name="filial",
            name="qtd_usuarios",
        ),
    ]
