# Generated by Django 4.1.13 on 2026-07-15 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoques', '0001_initial'),
        ('informacoes', '0001_initial'),
        ('filiais', '0004_alter_filial_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='filialestoque',
            name='estoque_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoques.estoque'),
        ),
        migrations.AddField(
            model_name='filialobservacao',
            name='observacao_nfe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='informacoes.informacoes'),
        ),
    ]
