# Generated by Django 4.1.13 on 2026-07-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0005_filialestoque_estoque_padrao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filialfiscal',
            name='cod_csc',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ID CSC'),
        ),
        migrations.AddField(
            model_name='filialfiscal',
            name='csc',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='CSC'),
        ),
    ]
