# Generated by Django 4.1.13 on 2025-11-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiais", "0005_remove_filial_qtd_filial_remove_filial_qtd_usuarios"),
    ]

    operations = [
        migrations.AddField(
            model_name="filial",
            name="layout_contrato",
            field=models.CharField(
                choices=[("Layout 1", "Layout 1"), ("Layout 2", "Layout 2")],
                default="Layout 1",
                max_length=10,
                verbose_name="Layout Contrato",
            ),
        ),
    ]
