# Generated by Django 4.1.13 on 2026-07-16 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0006_filialfiscal_cod_csc_filialfiscal_csc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filial',
            name='banco_fil',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='beneficiario',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='chave_pix',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='email',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='ft_juros',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='ft_multa',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='imp_recibo_cr',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='imp_recibo_orc',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='info_comp',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='info_local',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='info_orcamento',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='layout_contrato',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='layout_prod',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='max_dias_intervalo',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='max_parcelas',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='mt_qt_lam',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='multi_lg_corte1',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='multi_lg_corte2',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='multi_lg_corte3',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='multi_m2',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='tp_calc_juros',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='tp_calc_multa',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='tp_chave',
        ),
    ]
