# Generated by Django 4.1.13 on 2025-11-23 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("filiais", "0006_filial_layout_contrato"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuario",
            old_name="filial",
            new_name="filial_user",
        ),
    ]
