# Generated by Django 4.1.13 on 2026-02-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0007_rename_filial_usuario_filial_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='info_local',
            field=models.TextField(blank=True, default='Atendemos em todo estado do Pará!'),
        ),
    ]
