# Generated by Django 4.1.13 on 2026-07-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0007_remove_filial_banco_fil_remove_filial_beneficiario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='receber_alerta_estoque_maximo',
            field=models.BooleanField(default=False),
        ),
    ]
