# Generated by Django 4.1.13 on 2026-02-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiais", "0008_filial_info_local"),
    ]

    operations = [
        migrations.AddField(
            model_name="filial",
            name="max_parcelas",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
