# Generated by Django 4.1.13 on 2026-07-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0008_usuario_receber_alerta_estoque_maximo'),
    ]

    operations = [
        migrations.AddField(
            model_name='filialfiscal',
            name='autoridade_certificadora',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='filialfiscal',
            name='cnpj_certificado',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name='filialfiscal',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='filialfiscal',
            name='titular_certificado',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='filialfiscal',
            name='validade_certificado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
