# Generated by Django 4.1.13 on 2026-07-17 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formas_pgto', '0001_initial'),
        ('vendedores', '0001_initial'),
        ('tabelas_preco', '0001_initial'),
        ('filiais', '0009_filialfiscal_autoridade_certificadora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='desconto_maximo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='usuario',
            name='filiais_permitidas',
            field=models.ManyToManyField(blank=True, related_name='filiais_usuario', to='filiais.filial'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='formas_pagamento',
            field=models.ManyToManyField(blank=True, related_name='formas_usuario', to='formas_pgto.formapgto'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tabelas_preco',
            field=models.ManyToManyField(blank=True, related_name='tabelas_usuario', to='tabelas_preco.tabelapreco'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tel',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendedores.vendedor'),
        ),
    ]
