# Generated by Django 4.1.13 on 2026-02-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiais", "0009_filial_max_parcelas"),
    ]

    operations = [
        migrations.AddField(
            model_name="filial",
            name="ft_juros",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Fator Juros",
            ),
        ),
        migrations.AddField(
            model_name="filial",
            name="ft_multa",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Fator Multa",
            ),
        ),
        migrations.AddField(
            model_name="filial",
            name="tp_calc_juros",
            field=models.CharField(
                choices=[("Percentual", "Percentual"), ("Valor", "Valor")],
                default="Percentual",
                max_length=15,
                verbose_name="Tp. Cálculo Juros",
            ),
        ),
        migrations.AddField(
            model_name="filial",
            name="tp_calc_multa",
            field=models.CharField(
                choices=[("Percentual", "Percentual"), ("Valor", "Valor")],
                default="Percentual",
                max_length=15,
                verbose_name="Tp. Cálculo Multa",
            ),
        ),
    ]
