# Generated by Django 4.1.13 on 2026-03-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "filiais",
            "0010_filial_ft_juros_filial_ft_multa_filial_tp_calc_juros_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="filial",
            name="dt_criacao",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Data de Registro"
            ),
        ),
        migrations.AlterField(
            model_name="filial",
            name="dt_inativacao",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Data de Inativação"
            ),
        ),
    ]
