# Generated by Django 4.1.13 on 2026-07-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0010_usuario_desconto_maximo_usuario_filiais_permitidas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='opfilial',
            field=models.CharField(choices=[('0', 'Não'), ('1', 'Sim')], default='1', max_length=10, verbose_name='Acessar todas as filiais'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='opformas',
            field=models.CharField(choices=[('0', 'Não'), ('1', 'Sim')], default='1', max_length=10, verbose_name='Utilizar todas as formas de pagamento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='optabelas',
            field=models.CharField(choices=[('0', 'Não'), ('1', 'Sim')], default='1', max_length=10, verbose_name='Utilizar todas as tabelas de preço'),
        ),
    ]
