# Generated by Django 4.1.13 on 2026-03-16 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bancos", "0004_alter_banco_vinc_emp_banco_unique_banco_por_empresa"),
        ("filiais", "0011_alter_filial_dt_criacao_alter_filial_dt_inativacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filial",
            name="banco_fil",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bancos.banco",
            ),
        ),
        migrations.AlterField(
            model_name="filial",
            name="dt_criacao",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="Data de Registro"
            ),
        ),
        migrations.AlterField(
            model_name="filial",
            name="dt_inativacao",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="Data de Inativação"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="username",
            field=models.CharField(max_length=150),
        ),
    ]
