# Generated by Django 4.1.13 on 2026-07-18 01:12

from django.db import migrations, models
import filiais.models


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0011_usuario_opfilial_usuario_opformas_usuario_optabelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=filiais.models.caminho_foto_usuario),
        ),
    ]
