# Generated by Django 4.1.13 on 2026-07-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0012_alter_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='filialestoque',
            name='ativar_alerta_estoque',
            field=models.BooleanField(default=False),
        ),
    ]
