# Generated by Django 4.1.13 on 2026-03-30 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tecnicos", "0005_remove_tecnico_dt_reg_data_alter_tecnico_dt_reg"),
        ("clientes", "0004_alter_cliente_dt_reg_and_more"),
        ("filiais", "0012_alter_filial_banco_fil_alter_filial_dt_criacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filial",
            name="cli",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clientes.cliente",
            ),
        ),
        migrations.AddField(
            model_name="filial",
            name="tec",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tecnicos.tecnico",
            ),
        ),
    ]
