# Generated by Django 4.1.13 on 2026-08-02 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tecnicos", "0001_initial"),
        ("vendedores", "0001_initial"),
        ("filiais", "0013_filialestoque_ativar_alerta_estoque"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filial",
            name="tec",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tecnicos.tecnico",
            ),
        ),
        migrations.AlterField(
            model_name="filial",
            name="vendedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vendedores.vendedor",
            ),
        ),
    ]
