# Generated by Django 4.1.13 on 2026-03-31 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tabelas_preco", "0005_alter_tabelapreco_descricao_and_more"),
        ("filiais", "0013_filial_cli_filial_tec"),
    ]

    operations = [
        migrations.AddField(
            model_name="filial",
            name="tb_preco",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tabelas_preco.tabelapreco",
            ),
        ),
    ]
