# Generated by Django 4.1.13 on 2026-08-02 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bairros", "0001_initial"),
        ("filiais", "0014_alter_filial_tec_alter_filial_vendedor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filial",
            name="bairro_fil",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bairros.bairro",
            ),
        ),
    ]
