# Generated by Django 4.1.13 on 2026-04-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0014_filial_tb_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='max_dias_intervalo',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
