# Generated by Django 4.1.13 on 2026-04-19 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vendedores", "0001_initial"),
        ("filiais", "0015_filial_max_dias_intervalo"),
    ]

    operations = [
        migrations.AddField(
            model_name="filial",
            name="vendedor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vendedores.vendedor",
            ),
        ),
    ]
