# Generated by Django 4.1.13 on 2026-08-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiais", "0015_alter_filial_bairro_fil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="tel",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telefone"
            ),
        ),
    ]
