# Generated by Django 4.1.13 on 2026-08-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0016_alter_usuario_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='filialimpressao',
            name='imp_recibo_cp',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Auto', 'Auto')], default='Sim', max_length=20, verbose_name='Questionar Imp. de Recibo'),
        ),
    ]
