# Generated by Django 4.1.13 on 2026-04-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0016_filial_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='multi_m2',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True, verbose_name='Multiplicador M²'),
        ),
    ]
