# Generated by Django 4.1.13 on 2026-05-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0017_filial_multi_m2'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='agrupa_itens',
            field=models.BooleanField(default=True, verbose_name='Agrupar itens no pedido'),
        ),
    ]
