# Generated by Django 4.1.13 on 2026-08-06 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_cobranca', '0001_initial'),
        ('filiais', '0017_filialimpressao_imp_recibo_cp'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='tp_conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipo_cobranca.tipocobranca', verbose_name='Tipo de Conta'),
        ),
    ]
