# Generated by Django 4.1.13 on 2026-05-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0018_filial_agrupa_itens'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='multi_lg_corte1',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True, verbose_name='Multiplicador Lg. Corte (Fora do Vão)'),
        ),
        migrations.AddField(
            model_name='filial',
            name='multi_lg_corte2',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True, verbose_name='Multiplicador Lg. Corte (Dentro do Vão)'),
        ),
        migrations.AddField(
            model_name='filial',
            name='multi_lg_corte3',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True, verbose_name='Multiplicador Lg. Corte (1 Lado do Vão)'),
        ),
    ]
