# Generated by Django 4.1.13 on 2026-05-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0019_filial_multi_lg_corte1_filial_multi_lg_corte2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
