# Generated by Django 4.1.13 on 2026-05-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0020_filial_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='beneficiario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Beneficiário'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave Pix'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='email',
            field=models.EmailField(blank=True, max_length=40, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='ie',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='info_comp',
            field=models.TextField(blank=True, default='Obrigado pela preferência!', null=True),
        ),
        migrations.AlterField(
            model_name='filial',
            name='info_local',
            field=models.TextField(blank=True, default='Atendemos em todo estado do Pará!', null=True),
        ),
        migrations.AlterField(
            model_name='filial',
            name='info_orcamento',
            field=models.TextField(blank=True, default='*Caro cliente, caso você encontre um orçamento com valor inferior, podemos analisar o orçamento concorrente para fecharmos negócio.', null=True),
        ),
        migrations.AddConstraint(
            model_name='filial',
            constraint=models.UniqueConstraint(fields=('codigo', 'vinc_emp'), name='unique_codigo_filial_empresa'),
        ),
    ]
