# Generated by Django 4.1.13 on 2026-06-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiais", "0021_alter_filial_beneficiario_alter_filial_chave_pix_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="ver_res_orc",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usuario",
            name="ver_res_orc_tec",
            field=models.BooleanField(default=False),
        ),
    ]
