# Generated by Django 4.1.13 on 2026-06-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0022_usuario_ver_res_orc_usuario_ver_res_orc_tec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='senha_liberacao',
            field=models.CharField(blank=True, help_text='Para nova senha, preencha esse campo!', max_length=20, null=True, verbose_name='Senha de Liberação'),
        ),
    ]
