# Generated by Django 4.1.13 on 2026-07-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiais", "0023_alter_usuario_senha_liberacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="filial",
            name="mt_qt_lam",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=1,
                max_digits=10,
                null=True,
                verbose_name="Multip. Qtde. Lâminas",
            ),
        ),
    ]
