# Generated by Django 4.1.13 on 2026-07-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiais", "0024_filial_mt_qt_lam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filial",
            name="mt_qt_lam",
            field=models.CharField(
                blank=True,
                default="(alt_corte + rolo) / 0.075",
                max_length=100,
                null=True,
                verbose_name="Multip. Qtde. Lâminas",
            ),
        ),
    ]
