# Generated by Django 4.1.13 on 2026-07-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiais", "0025_alter_filial_mt_qt_lam"),
    ]

    operations = [
        migrations.AddField(
            model_name="filial",
            name="layout_prod",
            field=models.CharField(
                choices=[("1", "Layout 1"), ("2", "Layout 2")],
                default="1",
                max_length=10,
                verbose_name="L. PDF Produção",
            ),
        ),
    ]
