# Generated by Django 4.1.13 on 2026-07-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0026_filial_layout_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ver_caracteristicas_orcamentos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_conv_orc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_cores_orcamentos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_evolucao_orcamentos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_faturamento_diario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_formas_orcamentos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_peso_total',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_ranking_clientes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_ranking_tecnicos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_situacao_orcamentos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_situacao_valor_orcamentos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_status_orcamentos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_tempo_medio_faturamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_ticket_medio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_top_10_produtos_qtde',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_top_10_produtos_vl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_valor_perdido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_vl_total_faturado',
            field=models.BooleanField(default=False),
        ),
    ]
