# Generated by Django 4.1.13 on 2026-07-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0027_usuario_ver_caracteristicas_orcamentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ver_m2_total',
            field=models.BooleanField(default=False),
        ),
    ]
