# Generated by Django 4.1.13 on 2026-07-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0028_usuario_ver_m2_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='imp_recibo_orc',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Auto', 'Auto')], default='Sim', max_length=20, verbose_name='Questionar Imp. de Recibo'),
        ),
    ]
