# Generated by Django 4.1.13 on 2026-07-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiais', '0029_filial_imp_recibo_orc'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='imp_recibo_cr',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Auto', 'Auto')], default='Sim', max_length=20, verbose_name='Questionar Imp. de Recibo'),
        ),
    ]
