# Generated by Django 4.1.13 on 2025-10-24 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("formas_pgto", "0001_initial"),
        ("clientes", "0002_cliente_vinc_emp"),
        ("produtos", "0003_alter_produto_options"),
        ("filiais", "0005_remove_filial_qtd_filial_remove_filial_qtd_usuarios"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendedor", models.CharField(max_length=100)),
                ("nome_cli", models.CharField(blank=True, max_length=255)),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("Aberto", "Aberto"),
                            ("Faturado", "Faturado"),
                            ("Cancelado", "Cancelado"),
                        ],
                        default="Aberto",
                        max_length=10,
                    ),
                ),
                ("obs", models.TextField(blank=True, default="")),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("dt_emi", models.DateTimeField(blank=True, null=True)),
                ("dt_fat", models.DateTimeField(blank=True, null=True)),
                ("motivo", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "cli",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clientes.cliente",
                    ),
                ),
                (
                    "vinc_emp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="filiais.filial"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Pedidos",
                "permissions": [
                    ("clonar_pedido", "Pode clonar pedido"),
                    ("faturar_pedido", "Pode faturar pedido"),
                    ("cancelar_pedido", "Pode cancelar pedido"),
                    ("atribuir_desconto", "Pode atribuir descontos em pedido"),
                    ("atribuir_acrescimo", "Pode atribuir acréscimo em pedido"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PedidoProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "desc_acres",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Desconto/Acréscimo",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="pedidos.pedido",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produtos_vinculados_ped",
                        to="produtos.produto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PedidoFormaPgto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "formas_pgto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usos_ped",
                        to="formas_pgto.formapgto",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formas_pgto",
                        to="pedidos.pedido",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="pedidoformapgto",
            constraint=models.UniqueConstraint(
                fields=("pedido", "formas_pgto"), name="uniq_ped_formapgto"
            ),
        ),
    ]
