# Generated by Django 4.1.13 on 2026-07-15 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
        ('empresas', '0001_initial'),
        ('vendedores', '0001_initial'),
        ('formas_pgto', '0001_initial'),
        ('produtos', '0001_initial'),
        ('tabelas_preco', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('filiais', '0001_initial'),
        ('lancpdvs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(blank=True, null=True)),
                ('nome_cli', models.CharField(blank=True, max_length=255)),
                ('fantasia_fil', models.CharField(blank=True, max_length=255)),
                ('nome_vend', models.CharField(blank=True, max_length=255)),
                ('situacao', models.CharField(choices=[('Aberto', 'Aberto'), ('Faturado', 'Faturado'), ('Cancelado', 'Cancelado')], default='Aberto', max_length=10)),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('pago', 'Pago')], default='pendente', max_length=15)),
                ('obs', models.TextField(blank=True, default='')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dt_emi', models.DateTimeField(blank=True, null=True)),
                ('dt_fat', models.DateTimeField(blank=True, null=True)),
                ('dt_canc', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=60, null=True)),
                ('estoque_baixado', models.BooleanField(default=False)),
                ('tipo_operacao', models.CharField(choices=[('Venda', 'Venda'), ('Troca', 'Troca'), ('Devolucao', 'Devolução')], default='Venda', max_length=10)),
                ('caixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lancpdvs.caixa')),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('pedido_origem', models.ForeignKey(blank=True, help_text='Pedido original utilizado para uma troca ou devolução.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operacoes_relacionadas', to='pedidos.pedido')),
                ('tabela_preco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tabelas_preco.tabelapreco')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendedores.vendedor')),
                ('vinc_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('vinc_fil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filiais.filial')),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
                'permissions': [('clonar_pedido', 'Pode clonar pedido'), ('faturar_pedido', 'Pode faturar pedido'), ('cancelar_pedido', 'Pode cancelar pedido'), ('atribuir_desconto_ped', 'Pode atribuir descontos em pedido'), ('atribuir_acrescimo_ped', 'Pode atribuir acréscimos em pedido'), ('vender_sem_estoque_ped', 'Pode vender sem estoque'), ('alt_vl_ped', 'Pode alterar valor de produtos em pedidos'), ('alterar_data_faturamento', 'Pode alterar data de faturamento'), ('relatorio_pedidos', 'Pode acessar relatório de pedidos')],
            },
        ),
        migrations.CreateModel(
            name='PedidoDevolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('Troca', 'Troca'), ('Devolucao', 'Devolução')], max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observacao', models.TextField(blank=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='clientes.cliente')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='pedidos.pedido')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vinc_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('vinc_fil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filiais.filial')),
            ],
            options={
                'verbose_name': 'Troca / Devolução',
                'verbose_name_plural': 'Trocas / Devoluções',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='PedidoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_usado', models.CharField(blank=True, max_length=50, null=True)),
                ('vl_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tp_desc_acres', models.CharField(choices=[('Desconto', 'Desconto'), ('Acréscimo', 'Acréscimo')], default='Desconto', max_length=10)),
                ('tipo_desc', models.CharField(choices=[('valor', 'Valor'), ('percentual', 'Percentual')], default='valor', max_length=10)),
                ('desc_acres', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_vinculados_ped', to='produtos.produto')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoFormaPgto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('forma_pgto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formas_pgto.formapgto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas_pgto', to='pedidos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoDevolucaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devolucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedidodevolucao')),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_devolvidos', to='pedidos.pedidoproduto')),
            ],
            options={
                'verbose_name': 'Item da Devolução',
                'verbose_name_plural': 'Itens da Devolução',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('gateway', models.CharField(blank=True, max_length=20, null=True)),
                ('txid', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='pendente', max_length=20)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('qr_base64', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('dt_pagamento', models.DateTimeField(blank=True, null=True)),
                ('gateway_txid', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('forma_pgto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formas_pgto.formapgto')),
                ('vinc_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pedidoformapgto',
            constraint=models.UniqueConstraint(fields=('pedido', 'forma_pgto'), name='uniq_pedido_formapgto'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.UniqueConstraint(fields=('codigo', 'vinc_emp'), name='unique_codigo_pedido_empresa'),
        ),
    ]
