# Generated by Django 4.1.13 on 2025-10-24 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pedido",
            options={
                "permissions": [
                    ("clonar_pedido", "Pode clonar pedido"),
                    ("faturar_pedido", "Pode faturar pedido"),
                    ("cancelar_pedido", "Pode cancelar pedido"),
                    ("atribuir_desconto_ped", "Pode atribuir descontos em pedido"),
                    ("atribuir_acrescimo_ped", "Pode atribuir acréscimos em pedido"),
                ],
                "verbose_name_plural": "Pedidos",
            },
        ),
    ]
