# Generated by Django 4.1.13 on 2025-11-23 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0004_alter_empresa_principal"),
        ("filiais", "0007_rename_filial_usuario_filial_user"),
        ("pedidos", "0002_alter_pedido_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="vinc_fil",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="filiais.filial",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pedido",
            name="vinc_emp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="empresas.empresa"
            ),
        ),
    ]
