# Generated by Django 4.1.13 on 2026-02-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0003_pedido_vinc_fil_alter_pedido_vinc_emp"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedidoproduto",
            name="tp_desc_acres",
            field=models.CharField(
                choices=[("Desconto", "Desconto"), ("Acréscimo", "Acréscimo")],
                default="Desconto",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="pedidoproduto",
            name="vl_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Valor Unitário",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pedidoproduto",
            name="vl_unit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Valor Unitário",
            ),
            preserve_default=False,
        ),
    ]
