# Generated by Django 4.1.13 on 2026-03-18 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("filiais", "0012_alter_filial_banco_fil_alter_filial_dt_criacao_and_more"),
        ("clientes", "0004_alter_cliente_dt_reg_and_more"),
        ("pedidos", "0004_pedidoproduto_tp_desc_acres_pedidoproduto_vl_total_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="cli",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="clientes.cliente"
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="vinc_fil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="filiais.filial"
            ),
        ),
    ]
