# Generated by Django 4.1.13 on 2026-04-12 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formas_pgto', '0005_formapgto_credenciais_formapgto_gateway_and_more'),
        ('pedidos', '0005_alter_pedido_cli_alter_pedido_vinc_fil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=20)),
                ('txid', models.CharField(db_index=True, max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='pendente', max_length=20)),
                ('qr_code', models.TextField()),
                ('payload', models.JSONField(blank=True, null=True)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('dt_pagamento', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'permissions': [('clonar_pedido', 'Pode clonar pedido'), ('faturar_pedido', 'Pode faturar pedido'), ('cancelar_pedido', 'Pode cancelar pedido'), ('atribuir_desconto_ped', 'Pode atribuir descontos em pedido'), ('atribuir_acrescimo_ped', 'Pode atribuir acréscimos em pedido'), ('vender_sem_estoque_ped', 'Pode vender sem estoque')], 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.RemoveConstraint(
            model_name='pedidoformapgto',
            name='uniq_ped_formapgto',
        ),
        migrations.RemoveField(
            model_name='pedidoformapgto',
            name='formas_pgto',
        ),
        migrations.RemoveField(
            model_name='pedidoproduto',
            name='vl_total',
        ),
        migrations.AddField(
            model_name='pedido',
            name='status_pagamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('pago', 'Pago')], default='pendente', max_length=15),
        ),
        migrations.AddField(
            model_name='pedidoformapgto',
            name='forma_pgto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='formas_pgto.formapgto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidoproduto',
            name='desc_acres',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedidoproduto',
            name='vl_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='pedidoformapgto',
            constraint=models.UniqueConstraint(fields=('pedido', 'forma_pgto'), name='uniq_ped_formapgto'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='forma_pgto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formas_pgto.formapgto'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='pedidos.pedido'),
        ),
    ]
