# Generated by Django 4.1.13 on 2026-04-13 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabelas_preco', '0005_alter_tabelapreco_descricao_and_more'),
        ('pedidos', '0006_pagamento_alter_pedido_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'permissions': [('clonar_pedido', 'Pode clonar pedido'), ('faturar_pedido', 'Pode faturar pedido'), ('cancelar_pedido', 'Pode cancelar pedido'), ('atribuir_desconto_ped', 'Pode atribuir descontos em pedido'), ('atribuir_acrescimo_ped', 'Pode atribuir acréscimos em pedido'), ('vender_sem_estoque_ped', 'Pode vender sem estoque'), ('alt_vl_ped', 'Pode alterar valor de produtos em pedidos')], 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AddField(
            model_name='pedido',
            name='tabela_preco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tabelas_preco.tabelapreco'),
        ),
    ]
