# Generated by Django 4.1.13 on 2026-04-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_alter_pedido_options_pedido_tabela_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoproduto',
            name='vl_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
