# Generated by Django 4.1.13 on 2026-04-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_alter_pedidoproduto_vl_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fantasia_fil',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nome_vend',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
