# Generated by Django 4.1.13 on 2026-04-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_pedido_fantasia_fil_pedido_nome_vend'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproduto',
            name='tipo_desc',
            field=models.CharField(choices=[('valor', 'Valor'), ('percentual', 'Percentual')], default='valor', max_length=10),
        ),
    ]
