# Generated by Django 4.1.13 on 2026-04-16 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_pedidoproduto_tipo_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'permissions': [('clonar_pedido', 'Pode clonar pedido'), ('faturar_pedido', 'Pode faturar pedido'), ('cancelar_pedido', 'Pode cancelar pedido'), ('atribuir_desconto_ped', 'Pode atribuir descontos em pedido'), ('atribuir_acrescimo_ped', 'Pode atribuir acréscimos em pedido'), ('vender_sem_estoque_ped', 'Pode vender sem estoque'), ('alt_vl_ped', 'Pode alterar valor de produtos em pedidos'), ('alterar_data_faturamento', 'Pode alterar data de faturamento')], 'verbose_name_plural': 'Pedidos'},
        ),
    ]
