# Generated by Django 4.1.13 on 2026-04-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_alter_pedido_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='pedido_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
