# Generated by Django 4.1.13 on 2026-04-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0012_pagamento_pedido_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagamento",
            name="qr_base64",
            field=models.TextField(blank=True, null=True),
        ),
    ]
