# Generated by Django 4.1.13 on 2026-04-19 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vendedores", "0001_initial"),
        ("pedidos", "0013_pagamento_qr_base64"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="vendedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vendedores.vendedor",
            ),
        ),
    ]
