# Generated by Django 4.1.13 on 2026-04-25 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('empresas', '0009_empresa_senha_portal'),
        ('pedidos', '0014_alter_pedido_vendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='pedido_ref',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='vinc_emp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='gateway',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='txid',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
