# Generated by Django 4.1.13 on 2026-04-29 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lancpdvs', '0002_caixamovimento_pedido'),
        ('pedidos', '0015_remove_pagamento_pedido_remove_pagamento_pedido_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='caixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lancpdvs.caixa'),
        ),
    ]
