# Generated by Django 4.1.13 on 2026-05-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0016_pedido_caixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproduto',
            name='codigo_usado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
