# Generated by Django 4.1.13 on 2026-05-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_pedidoproduto_codigo_usado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estoque_baixado',
            field=models.BooleanField(default=False),
        ),
    ]
