# Generated by Django 4.1.13 on 2026-06-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0021_pedido_unique_codigo_pedido_empresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="dt_canc",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
