# Generated by Django 4.1.13 on 2026-07-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0022_pedido_dt_canc"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagamento",
            name="gateway_txid",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
    ]
