# Generated by Django 4.1.13 on 2026-07-09 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_creditocliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresas', '0009_empresa_senha_portal'),
        ('filiais', '0030_filial_imp_recibo_cr'),
        ('pedidos', '0024_pedido_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoDevolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('Troca', 'Troca'), ('Devolucao', 'Devolução')], max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observacao', models.TextField(blank=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Troca / Devolução',
                'verbose_name_plural': 'Trocas / Devoluções',
                'ordering': ['-data'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='pedido_origem',
            field=models.ForeignKey(blank=True, help_text='Pedido original utilizado para uma troca ou devolução.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operacoes_relacionadas', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_operacao',
            field=models.CharField(choices=[('Venda', 'Venda'), ('Troca', 'Troca'), ('Devolucao', 'Devolução')], default='Venda', max_length=10),
        ),
        migrations.CreateModel(
            name='PedidoDevolucaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devolucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedidodevolucao')),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='pedidos.pedidoproduto')),
            ],
            options={
                'verbose_name': 'Item da Devolução',
                'verbose_name_plural': 'Itens da Devolução',
            },
        ),
        migrations.AddField(
            model_name='pedidodevolucao',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='pedidodevolucao',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedidodevolucao',
            name='vinc_emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='pedidodevolucao',
            name='vinc_fil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filiais.filial'),
        ),
    ]
