# Generated by Django 4.1.13 on 2026-07-10 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0025_pedidodevolucao_pedido_pedido_origem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodevolucaoitem',
            name='item_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_devolvidos', to='pedidos.pedidoproduto'),
        ),
    ]
