# Generated by Django 4.1.13 on 2026-07-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_imp', models.CharField(max_length=200)),
                ('qtd_usu', models.IntegerField()),
                ('vl_imp', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('dsct_imp', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('vl_fin_imp', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('desc_ass', models.CharField(max_length=200)),
                ('vl_ass', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('qtd_ass', models.IntegerField()),
                ('dsct_ass', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('vl_fin_ass', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('dt_emi', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('data_confirmacao', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('nome_emp', models.CharField(max_length=100)),
                ('obs', models.TextField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('Aberta', 'Aberta'), ('Confirmada', 'Confirmada')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Propostas',
            },
        ),
    ]
