# Generated by Django 4.1.13 on 2026-06-17 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposta',
            old_name='descricao',
            new_name='desc_imp',
        ),
    ]
