# Generated by Django 4.1.13 on 2025-09-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_banco", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "cod_banco",
                    models.CharField(max_length=100, verbose_name="Código Banco"),
                ),
            ],
            options={
                "verbose_name_plural": "Bancos",
            },
        ),
    ]
