# Generated by Django 4.1.13 on 2025-11-23 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0002_alter_empresa_qtd_filial"),
        ("bancos", "0002_banco_vinc_emp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banco",
            name="vinc_emp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="empresas.empresa",
            ),
        ),
    ]
