# Generated by Django 4.1.13 on 2026-03-15 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0009_empresa_senha_portal"),
        ("bancos", "0003_alter_banco_vinc_emp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banco",
            name="vinc_emp",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="empresas.empresa",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="banco",
            constraint=models.UniqueConstraint(
                fields=("nome_banco", "vinc_emp"), name="unique_banco_por_empresa"
            ),
        ),
    ]
