# Generated by Django 4.1.13 on 2026-07-15 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cidades', '0001_initial'),
        ('bairros', '0001_initial'),
        ('estados', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=10, verbose_name='Situação')),
                ('pessoa', models.CharField(choices=[('Física', 'Física'), ('Jurídica', 'Jurídica')], max_length=10, verbose_name='Pessoa')),
                ('cpf_cnpj', models.CharField(max_length=25)),
                ('ie', models.CharField(blank=True, max_length=20, null=True)),
                ('razao_social', models.CharField(max_length=100)),
                ('fantasia', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=10)),
                ('complem', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('tel', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=40, null=True)),
                ('dt_reg', models.DateField(blank=True, db_index=True, null=True, verbose_name='Data de Registro')),
                ('bairro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bairros.bairro')),
                ('cidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cidades.cidade')),
                ('uf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estados.estado')),
                ('vinc_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
            options={
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.AddConstraint(
            model_name='fornecedor',
            constraint=models.UniqueConstraint(fields=('cpf_cnpj', 'vinc_emp'), name='unique_cpf_cnpj_fornecedor_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='fornecedor',
            constraint=models.UniqueConstraint(fields=('codigo', 'vinc_emp'), name='unique_codigo_fornecedor_empresa'),
        ),
    ]
