# Generated by Django 4.1.13 on 2025-09-27 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("filiais", "0005_remove_filial_qtd_filial_remove_filial_qtd_usuarios"),
        ("fornecedores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fornecedor",
            name="vinc_emp",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="filiais.filial",
            ),
            preserve_default=False,
        ),
    ]
