# Generated by Django 4.1.13 on 2026-03-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fornecedores", "0003_alter_fornecedor_vinc_emp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fornecedor",
            name="dt_reg",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="Data de Registro"
            ),
        ),
    ]
