# Generated by Django 4.1.13 on 2026-05-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0004_alter_fornecedor_dt_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
