# Generated by Django 4.1.13 on 2025-09-25 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contratos", "0001_initial"),
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mensalidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[("Aberta", "Aberta"), ("Baixada", "Baixada")],
                        default="Aberta",
                        max_length=10,
                    ),
                ),
                (
                    "num_mens",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Nr. Mensalidade",
                    ),
                ),
                ("dt_venc", models.DateField(blank=True, null=True)),
                ("dt_pag", models.DateField(blank=True, null=True)),
                (
                    "tp_mens",
                    models.CharField(
                        choices=[("Boleto", "Boleto"), ("Pix", "Pix")],
                        default="Pix",
                        max_length=10,
                    ),
                ),
                ("qtd_mens", models.IntegerField()),
                ("vl_mens", models.DecimalField(decimal_places=2, max_digits=10)),
                ("obs", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contratos.contrato",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Mensalidades",
                "ordering": ["-dt_venc"],
            },
        ),
    ]
