# Generated by Django 4.1.13 on 2026-07-15 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(choices=[('Aberta', 'Aberta'), ('Baixada', 'Baixada')], default='Aberta', max_length=10)),
                ('num_mens', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nr. Mensalidade')),
                ('dt_venc', models.DateField()),
                ('dt_pag', models.DateField(blank=True, null=True)),
                ('tp_mens', models.CharField(choices=[('Boleto', 'Boleto'), ('Pix', 'Pix')], default='Pix', max_length=10)),
                ('vl_mens', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vl_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tp_juros', models.CharField(choices=[('Percentual', 'Percentual'), ('Valor', 'Valor')], default='Percentual', max_length=15, verbose_name='Tp. Cálculo Juros')),
                ('tp_multa', models.CharField(choices=[('Percentual', 'Percentual'), ('Valor', 'Valor')], default='Percentual', max_length=15, verbose_name='Tp. Cálculo Multa')),
                ('vl_multa', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('vl_juros', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('codigo_boleto', models.CharField(blank=True, max_length=100, null=True)),
                ('pix_txid', models.CharField(blank=True, max_length=100, null=True)),
                ('pix_cobranca_id', models.CharField(blank=True, max_length=120, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contratos.contrato')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
            options={
                'verbose_name_plural': 'Mensalidades',
                'ordering': ['-dt_venc'],
            },
        ),
        migrations.CreateModel(
            name='CobrancaPix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_payment_id', models.CharField(max_length=120, unique=True)),
                ('qr_code', models.TextField()),
                ('qr_code_base64', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('mensalidades', models.ManyToManyField(to='mensalidades.mensalidade')),
            ],
        ),
        migrations.AddIndex(
            model_name='mensalidade',
            index=models.Index(fields=['situacao'], name='mensalidade_situaca_49a204_idx'),
        ),
        migrations.AddIndex(
            model_name='mensalidade',
            index=models.Index(fields=['dt_venc'], name='mensalidade_dt_venc_b4c795_idx'),
        ),
        migrations.AddIndex(
            model_name='mensalidade',
            index=models.Index(fields=['empresa'], name='mensalidade_empresa_d23302_idx'),
        ),
    ]
