# Generated by Django 4.1.13 on 2026-02-05 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mensalidades", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mensalidade",
            name="qtd_mens",
        ),
        migrations.AddField(
            model_name="mensalidade",
            name="codigo_boleto",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="mensalidade",
            name="pix_txid",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="mensalidade",
            name="vl_juros",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="mensalidade",
            name="vl_multa",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="mensalidade",
            name="vl_pago",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="mensalidade",
            name="dt_venc",
            field=models.DateField(default=datetime.date(2026, 2, 5)),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="mensalidade",
            index=models.Index(
                fields=["situacao"], name="mensalidade_situaca_49a204_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mensalidade",
            index=models.Index(
                fields=["dt_venc"], name="mensalidade_dt_venc_b4c795_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mensalidade",
            index=models.Index(
                fields=["empresa"], name="mensalidade_empresa_d23302_idx"
            ),
        ),
    ]
