# Generated by Django 4.1.13 on 2026-02-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mensalidades", "0002_remove_mensalidade_qtd_mens_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mensalidade",
            name="vl_juros",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mensalidade",
            name="vl_multa",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
