# Generated by Django 4.1.13 on 2026-02-09 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0004_rename_qtd_parcelas_contrato_qtd_meses"),
        ("mensalidades", "0003_alter_mensalidade_vl_juros_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mensalidade",
            name="contrato",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contratos.contrato",
            ),
        ),
    ]
