# Generated by Django 4.1.13 on 2026-02-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mensalidades", "0004_alter_mensalidade_contrato"),
    ]

    operations = [
        migrations.AddField(
            model_name="mensalidade",
            name="tp_juros",
            field=models.CharField(
                choices=[("Percentual", "Percentual"), ("Valor", "Valor")],
                default="Percentual",
                max_length=15,
                verbose_name="Tp. Cálculo Juros",
            ),
        ),
        migrations.AddField(
            model_name="mensalidade",
            name="tp_multa",
            field=models.CharField(
                choices=[("Percentual", "Percentual"), ("Valor", "Valor")],
                default="Percentual",
                max_length=15,
                verbose_name="Tp. Cálculo Multa",
            ),
        ),
    ]
