# Generated by Django 4.1.13 on 2026-02-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mensalidades", "0005_mensalidade_tp_juros_mensalidade_tp_multa"),
    ]

    operations = [
        migrations.AddField(
            model_name="mensalidade",
            name="pix_cobranca_id",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
