# Generated by Django 4.1.13 on 2026-02-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mensalidades", "0006_mensalidade_pix_cobranca_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CobrancaPix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mp_payment_id", models.CharField(max_length=120)),
                ("qr_code", models.TextField()),
                ("qr_code_base64", models.TextField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("pago", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("mensalidades", models.ManyToManyField(to="mensalidades.mensalidade")),
            ],
        ),
    ]
