# Generated by Django 4.1.13 on 2026-02-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mensalidades", "0007_cobrancapix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cobrancapix",
            name="mp_payment_id",
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
