# Generated by Django 4.1.13 on 2026-07-15 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_local', models.PositiveIntegerField(blank=True, null=True)),
                ('codigo', models.CharField(help_text='Identificador interno da regra (ex: MOTOR, LAMINA, PINTURA)', max_length=50)),
                ('descricao', models.CharField(help_text='Descrição legível da regra', max_length=100)),
                ('tipo', models.CharField(choices=[('QTD', 'Cálculo de Quantidade'), ('SELECAO', 'Seleção Automática')], max_length=20)),
                ('tipo_regra', models.CharField(blank=True, choices=[('', ''), ('qtd', 'Quantidade (múltiplos produtos)'), ('peso', 'Por Peso (máx)'), ('simples', 'Valor Simples')], max_length=20, null=True)),
                ('expressao_json', models.JSONField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.produto', verbose_name='Produto')),
                ('vinc_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
            options={
                'verbose_name_plural': 'Regras de Produto',
            },
        ),
        migrations.AddConstraint(
            model_name='regraproduto',
            constraint=models.UniqueConstraint(fields=('codigo', 'vinc_emp'), name='unique_codigo_regra_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='regraproduto',
            constraint=models.UniqueConstraint(fields=('cod_local', 'vinc_emp'), name='unique_cod_local_regra_empresa'),
        ),
    ]
