# Generated by Django 4.1.13 on 2026-01-07 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0004_alter_empresa_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Identificador interno da regra (ex: MOTOR, LAMINA, PINTURA)', max_length=50, unique=True)),
                ('descricao', models.CharField(help_text='Descrição legível da regra', max_length=100)),
                ('tipo', models.CharField(choices=[('QTD', 'Cálculo de Quantidade'), ('SELECAO', 'Seleção Automática')], max_length=20)),
                ('expressao', models.TextField(help_text='Fórmula ou regra (ex: m2, alt_c * 4, JSON para seleção)')),
                ('ativo', models.BooleanField(default=True)),
                ('vinc_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
        ),
    ]
