# Generated by Django 4.1.13 on 2026-07-20 14:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('produtos', '0003_alter_alerta_tipo'),
        ('regras_produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regraproduto',
            options={'ordering': ['categoria', 'ordem', 'codigo'], 'verbose_name': 'Regra de Produto', 'verbose_name_plural': 'Regras de Produto'},
        ),
        migrations.AddField(
            model_name='regraproduto',
            name='alterado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='regraproduto',
            name='categoria',
            field=models.CharField(choices=[('lamina', 'Lâmina'), ('motor', 'Motor / Acionamento'), ('pintura', 'Pintura / Acabamento'), ('fixacao', 'Fixação / Estrutura'), ('acessorio', 'Acessório'), ('outro', 'Outro')], default='outro', help_text='Categoria do componente (usada para agrupar no orçamento)', max_length=20),
        ),
        migrations.AddField(
            model_name='regraproduto',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regraproduto',
            name='ordem',
            field=models.PositiveSmallIntegerField(default=0, help_text='Prioridade de avaliação quando múltiplas regras do mesmo código existem. Menor = avaliado primeiro.'),
        ),
        migrations.AlterField(
            model_name='regraproduto',
            name='codigo',
            field=models.CharField(help_text='Identificador único por empresa (ex: MOTOR, LAMINA, PINTURA_EPOX)', max_length=50),
        ),
        migrations.AlterField(
            model_name='regraproduto',
            name='descricao',
            field=models.CharField(help_text='Descrição legível da regra', max_length=150),
        ),
        migrations.AlterField(
            model_name='regraproduto',
            name='expressao_json',
            field=models.JSONField(blank=True, help_text='Array JSON de itens. Cada item tem: produto_id, desc_prod, qtd_expr e (para SELECAO) condicoes.', null=True),
        ),
        migrations.AlterField(
            model_name='regraproduto',
            name='produto',
            field=models.ForeignKey(blank=True, help_text='Preenchido apenas quando a regra tem produto único (tipo OPCIONAL).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.produto', verbose_name='Produto fixo'),
        ),
        migrations.AlterField(
            model_name='regraproduto',
            name='tipo',
            field=models.CharField(choices=[('QTD', 'Cálculo de Quantidade'), ('SELECAO', 'Seleção Automática'), ('OPCIONAL', 'Acessório Opcional')], help_text='QTD: calcula quantidade via fórmula. SELECAO: escolhe o produto certo automaticamente. OPCIONAL: acessório exibido para o usuário escolher.', max_length=20),
        ),
        migrations.AlterField(
            model_name='regraproduto',
            name='tipo_regra',
            field=models.CharField(blank=True, choices=[('', '—'), ('simples', 'Condição Simples (igual a)'), ('faixa', 'Por Faixa Numérica'), ('peso_max', 'Por Peso Máximo (escalonado)'), ('composto', 'Condição Composta (AND)'), ('qtd', 'Quantidade por Fórmula')], default='', help_text='Subtipo de avaliação (obrigatório para SELECAO e QTD)', max_length=20),
        ),
        migrations.AlterField(
            model_name='regraproduto',
            name='vinc_emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_produto', to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddIndex(
            model_name='regraproduto',
            index=models.Index(fields=['vinc_emp', 'ativo', 'categoria'], name='regras_prod_vinc_em_399a74_idx'),
        ),
    ]
