# Generated by Django 4.1.13 on 2026-01-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_alter_empresa_principal'),
        ('regras_produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regraproduto',
            name='codigo',
            field=models.CharField(help_text='Identificador interno da regra (ex: MOTOR, LAMINA, PINTURA)', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='regraproduto',
            unique_together={('vinc_emp', 'codigo')},
        ),
    ]
