# Generated by Django 4.1.13 on 2026-03-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regras_produto", "0002_alter_regraproduto_codigo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="regraproduto",
            options={"verbose_name_plural": "Regras de Produto"},
        ),
        migrations.AlterUniqueTogether(
            name="regraproduto",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="regraproduto",
            constraint=models.UniqueConstraint(
                fields=("codigo", "vinc_emp"), name="unique_codigo_regra_por_empresa"
            ),
        ),
    ]
