# Generated by Django 4.1.13 on 2026-07-20 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_orcamento_dt_prev_instalacao_orcamento_prioridade_and_more'),
        ('empresas', '0001_initial'),
        ('produtos', '0003_alter_alerta_tipo'),
        ('regras_produto', '0002_alter_regraproduto_options_regraproduto_alterado_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueioRegraProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CondicaoRegraProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=50)),
                ('operador', models.CharField(choices=[('=', 'Igual'), ('>', 'Maior'), ('<', 'Menor'), ('>=', 'Maior ou igual'), ('<=', 'Menor ou igual'), ('IN', 'Está entre')], max_length=5)),
                ('valor', models.JSONField()),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='GrupoRegraProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordem', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='RegraProdutoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula_qtd', models.CharField(default='1', help_text='Ex: ceil(area/0.8)', max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=150)),
                ('prioridade', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['prioridade'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoRegraPorta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('contexto', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='regraproduto',
            options={'ordering': ['grupo', 'ordem', 'codigo']},
        ),
        migrations.AlterField(
            model_name='regraproduto',
            name='categoria',
            field=models.CharField(choices=[('lamina', 'Lâmina'), ('motor', 'Motor'), ('eixo', 'Eixo'), ('mola', 'Mola'), ('pintura', 'Pintura'), ('acessorio', 'Acessório'), ('outro', 'Outro')], default='outro', max_length=30),
        ),
        migrations.AlterField(
            model_name='regraproduto',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='regraproduto',
            name='descricao',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='regraproduto',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='regraproduto',
            name='tipo',
            field=models.CharField(choices=[('SELECAO', 'Selecionar Produto'), ('CALCULO', 'Calcular Quantidade'), ('ADICIONAL', 'Adicionar Item'), ('VALIDACAO', 'Validação')], max_length=20),
        ),
        migrations.AlterField(
            model_name='regraproduto',
            name='vinc_emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_produto', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='resultadoregraporta',
            name='porta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_regras', to='orcamentos.portaorcamento'),
        ),
        migrations.AddField(
            model_name='resultadoregraporta',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto'),
        ),
        migrations.AddField(
            model_name='resultadoregraporta',
            name='regra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regras_produto.regraproduto'),
        ),
        migrations.AddField(
            model_name='regraprodutoitem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto'),
        ),
        migrations.AddField(
            model_name='regraprodutoitem',
            name='regra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='regras_produto.regraproduto'),
        ),
        migrations.AddField(
            model_name='gruporegraproduto',
            name='vinc_emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_regras_produto', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='condicaoregraproduto',
            name='regra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condicoes', to='regras_produto.regraproduto'),
        ),
        migrations.AddField(
            model_name='bloqueioregraproduto',
            name='regra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to='regras_produto.regraproduto'),
        ),
        migrations.AddField(
            model_name='regraproduto',
            name='grupo',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='regras', to='regras_produto.gruporegraproduto'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='resultadoregraporta',
            index=models.Index(fields=['porta', 'regra'], name='regras_prod_porta_i_4d2954_idx'),
        ),
        migrations.AddConstraint(
            model_name='gruporegraproduto',
            constraint=models.UniqueConstraint(fields=('vinc_emp', 'codigo'), name='unique_grupo_regra_empresa'),
        ),
    ]
