# Generated by Django 4.1.13 on 2026-07-20 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_alerta_tipo'),
        ('regras_produto', '0003_bloqueioregraproduto_condicaoregraproduto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regraproduto',
            name='formula',
            field=models.JSONField(blank=True, help_text='Somente fórmulas e parâmetros extras', null=True),
        ),
        migrations.AlterField(
            model_name='regraproduto',
            name='expressao_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regraproduto',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.produto', verbose_name='Produto'),
        ),
        migrations.AddIndex(
            model_name='regraproduto',
            index=models.Index(fields=['vinc_emp'], name='regras_prod_vinc_em_701791_idx'),
        ),
        migrations.AddIndex(
            model_name='regraproduto',
            index=models.Index(fields=['grupo'], name='regras_prod_grupo_i_eba510_idx'),
        ),
    ]
