# Generated by Django 4.1.13 on 2026-03-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regras_produto", "0003_alter_regraproduto_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regraproduto",
            name="expressao",
            field=models.TextField(
                help_text="Fórmula ou regra (ex: m2 = M², larg = Largura, alt = Altura, larg_c = Largura de Corte, alt_c = Altura de Corte, ft_peso = Fator de Peso, qtd_lam = Quantidade de Lâminas, eix_mot = Eixo do Motor, alt_c * 4, JSON para seleção com a descrição do produto)"
            ),
        ),
    ]
