# Generated by Django 4.1.13 on 2026-07-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regras_produto', '0004_remove_regraproduto_regras_prod_vinc_em_399a74_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruporegraproduto',
            name='cod_local',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
