# Generated by Django 4.1.13 on 2026-04-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regras_produto", "0004_alter_regraproduto_expressao"),
    ]

    operations = [
        migrations.AddField(
            model_name="regraproduto",
            name="expressao_json",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
