# Generated by Django 4.1.13 on 2026-04-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regras_produto", "0005_regraproduto_expressao_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="regraproduto",
            name="tipo_regra",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("peso", "Por Peso (máx)"),
                    ("simples", "Valor Simples"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
