# Generated by Django 4.1.13 on 2026-07-20 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regras_produto', '0005_remove_regraproduto_regras_prod_vinc_em_399a74_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='regraproduto',
            name='regras_prod_vinc_em_399a74_idx',
        ),
        migrations.RemoveField(
            model_name='condicaoregraproduto',
            name='regra',
        ),
        migrations.RemoveField(
            model_name='regraproduto',
            name='expressao_json',
        ),
        migrations.RemoveField(
            model_name='regraproduto',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='regraproduto',
            name='tipo_regra',
        ),
        migrations.AddField(
            model_name='condicaoregraproduto',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='condicoes', to='regras_produto.regraprodutoitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='regraprodutoitem',
            name='formula_qtd',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
