# Generated by Django 4.1.13 on 2026-04-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regras_produto", "0006_regraproduto_tipo_regra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regraproduto",
            name="expressao",
            field=models.TextField(
                blank=True,
                help_text="Fórmula ou regra (ex: m2 = M², larg = Largura, alt = Altura, larg_c = Largura de Corte, alt_c = Altura de Corte, ft_peso = Fator de Peso, qtd_lam = Quantidade de Lâminas, eix_mot = Eixo do Motor, alt_c * 4, JSON para seleção com a descrição do produto)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="regraproduto",
            name="expressao_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
