# Generated by Django 4.1.13 on 2026-07-20 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regras_produto', '0006_remove_regraproduto_regras_prod_vinc_em_399a74_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condicaoregraproduto',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condicoes', to='regras_produto.regraprodutoitem'),
        ),
    ]
