# Generated by Django 4.1.13 on 2026-04-10 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0022_remove_produto_regra'),
        ('regras_produto', '0007_alter_regraproduto_expressao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regraproduto',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.produto'),
        ),
    ]
