# Generated by Django 4.1.13 on 2026-07-21 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regras_produto', '0007_condicaoregraproduto_regra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condicaoregraproduto',
            name='regra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condicoes', to='regras_produto.regraproduto'),
        ),
        migrations.AlterField(
            model_name='regraproduto',
            name='categoria',
            field=models.CharField(choices=[('lamina', 'Lâmina'), ('motor', 'Motor'), ('eixo', 'Eixo'), ('mola', 'Mola'), ('pintura', 'Pintura'), ('testeira', 'Testeira'), ('acessorio', 'Acessório'), ('outro', 'Outro')], default='outro', max_length=30),
        ),
    ]
