# Generated by Django 4.1.13 on 2026-04-10 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0022_remove_produto_regra'),
        ('regras_produto', '0008_regraproduto_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regraproduto',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.produto', verbose_name='Produto'),
        ),
    ]
