# Generated by Django 4.1.13 on 2026-04-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regras_produto', '0009_alter_regraproduto_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regraproduto',
            name='tipo_regra',
            field=models.CharField(blank=True, choices=[('', ''), ('qtd', 'Quantidade (múltiplos produtos)'), ('peso', 'Por Peso (máx)'), ('simples', 'Valor Simples')], max_length=20, null=True),
        ),
    ]
