# Generated by Django 4.1.13 on 2026-04-10 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regras_produto', '0010_alter_regraproduto_tipo_regra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regraproduto',
            name='expressao',
        ),
    ]
