# Generated by Django 4.1.13 on 2026-05-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regras_produto', '0011_remove_regraproduto_expressao'),
    ]

    operations = [
        migrations.AddField(
            model_name='regraproduto',
            name='cod_local',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
