# Generated by Django 4.1.13 on 2026-05-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regras_produto', '0012_regraproduto_cod_local'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='regraproduto',
            constraint=models.UniqueConstraint(fields=('cod_local', 'vinc_emp'), name='unique_cod_local_regra_empresa'),
        ),
    ]
