# Generated by Django 4.1.13 on 2026-02-22 01:54

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orcamentos", "0026_orcamentoformapgto_dias_intervalo_and_more"),
        ("formas_pgto", "0004_alter_formapgto_troco"),
        ("clientes", "0003_alter_cliente_vinc_emp"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContaReceber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_parcela", models.PositiveIntegerField(default=1)),
                ("total_parcelas", models.PositiveIntegerField(default=1)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "valor_pago",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "juros",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "multa",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "desconto",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("data_emissao", models.DateField(auto_now_add=True)),
                ("data_vencimento", models.DateField()),
                ("data_pagamento", models.DateField(blank=True, null=True)),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("Aberto", "Aberto"),
                            ("Pago", "Pago"),
                            ("Parcial", "Pago Parcial"),
                            ("Cancelado", "Cancelado"),
                        ],
                        default="Aberto",
                        max_length=10,
                    ),
                ),
                ("observacao", models.CharField(blank=True, max_length=255)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contas_receber",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "forma_pgto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="formas_pgto.formapgto",
                    ),
                ),
                (
                    "orcamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="titulos",
                        to="orcamentos.orcamento",
                    ),
                ),
            ],
        ),
    ]
