# Generated by Django 4.1.13 on 2026-07-15 19:47

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empresas', '0001_initial'),
        ('formas_pgto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(blank=True, null=True)),
                ('num_conta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Conta')),
                ('tp_juros', models.CharField(choices=[('Percentual', 'Percentual'), ('Valor', 'Valor')], default='Percentual', max_length=15, verbose_name='Tp. Cálculo Juros')),
                ('tp_multa', models.CharField(choices=[('Percentual', 'Percentual'), ('Valor', 'Valor')], default='Percentual', max_length=15, verbose_name='Tp. Cálculo Multa')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('juros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('multa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('data_emissao', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('Aberta', 'Aberta'), ('Paga', 'Paga')], default='Aberta', max_length=14)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('obs_internas', models.TextField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True, default='', null=True)),
                ('tipo', models.CharField(choices=[('Original', 'Original'), ('Remanescente', 'Remanescente')], default='Original', max_length=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber_orc', to='clientes.cliente')),
                ('forma_pgto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='formas_pgto.formapgto')),
            ],
            options={
                'verbose_name_plural': 'Contas à Receber',
                'permissions': [('atribuir_desconto_cr', 'Pode aplicar descontos em contas à pagar'), ('baixar_cr', 'Pode realizar baixa em contas à pagar'), ('estornar_cr', 'Pode realizar estorno em contas à pagar')],
            },
        ),
        migrations.CreateModel(
            name='ContaReceberBaixaForma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('conta_receber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas_baixa', to='contas_receber.contareceber')),
                ('forma_pgto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formas_pgto.formapgto')),
                ('vinc_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Forma de pagamento da baixa',
                'verbose_name_plural': 'Formas de pagamento da baixa',
            },
        ),
    ]
