# Generated by Django 4.1.13 on 2026-02-24 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0009_empresa_senha_portal"),
        ("orcamentos", "0026_orcamentoformapgto_dias_intervalo_and_more"),
        ("pedidos", "0004_pedidoproduto_tp_desc_acres_pedidoproduto_vl_total_and_more"),
        (
            "filiais",
            "0010_filial_ft_juros_filial_ft_multa_filial_tp_calc_juros_and_more",
        ),
        ("clientes", "0003_alter_cliente_vinc_emp"),
        ("contas_receber", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contareceber",
            name="numero_parcela",
        ),
        migrations.RemoveField(
            model_name="contareceber",
            name="total_parcelas",
        ),
        migrations.AddField(
            model_name="contareceber",
            name="num_conta",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Nº Conta"
            ),
        ),
        migrations.AddField(
            model_name="contareceber",
            name="pedido",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="titulos_pedidos",
                to="pedidos.pedido",
            ),
        ),
        migrations.AddField(
            model_name="contareceber",
            name="tp_juros",
            field=models.CharField(
                choices=[("Percentual", "Percentual"), ("Valor", "Valor")],
                default="Percentual",
                max_length=15,
                verbose_name="Tp. Cálculo Juros",
            ),
        ),
        migrations.AddField(
            model_name="contareceber",
            name="tp_multa",
            field=models.CharField(
                choices=[("Percentual", "Percentual"), ("Valor", "Valor")],
                default="Percentual",
                max_length=15,
                verbose_name="Tp. Cálculo Multa",
            ),
        ),
        migrations.AddField(
            model_name="contareceber",
            name="vinc_emp",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="empresas.empresa",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contareceber",
            name="vinc_fil",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="filiais.filial",
            ),
        ),
        migrations.AlterField(
            model_name="contareceber",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contas_receber_orc",
                to="clientes.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="contareceber",
            name="observacao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contareceber",
            name="orcamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="titulos_orc",
                to="orcamentos.orcamento",
            ),
        ),
        migrations.AlterField(
            model_name="contareceber",
            name="situacao",
            field=models.CharField(
                choices=[("Aberta", "Aberta"), ("Paga", "Paga")],
                default="Aberta",
                max_length=14,
            ),
        ),
    ]
