# Generated by Django 4.1.13 on 2026-07-15 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orcamentos', '0001_initial'),
        ('contas_receber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos_orc', to='orcamentos.orcamento'),
        ),
    ]
