# Generated by Django 4.1.13 on 2026-02-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contas_receber", "0002_remove_contareceber_numero_parcela_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contareceber",
            options={
                "permissions": [
                    (
                        "atribuir_desconto_cr",
                        "Pode aplicar descontos em contas à pagar",
                    ),
                    ("baixar_cr", "Pode realizar baixa em contas à pagar"),
                    ("estornar_cr", "Pode realizar estorno em contas à pagar"),
                ],
                "verbose_name_plural": "Contas à Receber",
            },
        ),
    ]
