# Generated by Django 4.1.13 on 2026-07-15 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filiais', '0001_initial'),
        ('empresas', '0001_initial'),
        ('contas_receber', '0002_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos_pedidos', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='titulo_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titulos_remanescentes', to='contas_receber.contareceber'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='vinc_emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='vinc_fil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filiais.filial'),
        ),
        migrations.AddConstraint(
            model_name='contareceber',
            constraint=models.UniqueConstraint(fields=('codigo', 'vinc_emp'), name='unique_codigo_conta_receber_empresa'),
        ),
    ]
