# Generated by Django 4.1.13 on 2026-02-24 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("formas_pgto", "0004_alter_formapgto_troco"),
        ("contas_receber", "0003_alter_contareceber_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contareceber",
            name="forma_pgto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="formas_pgto.formapgto",
            ),
        ),
    ]
