# Generated by Django 4.1.13 on 2026-03-15 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("filiais", "0011_alter_filial_dt_criacao_alter_filial_dt_inativacao"),
        ("contas_receber", "0004_alter_contareceber_forma_pgto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contareceber",
            name="vinc_fil",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="filiais.filial",
            ),
        ),
    ]
