# Generated by Django 4.1.13 on 2026-03-30 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0009_empresa_senha_portal"),
        ("formas_pgto", "0004_alter_formapgto_troco"),
        ("contas_receber", "0005_alter_contareceber_vinc_fil"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContaReceberBaixaForma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "conta_receber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formas_baixa",
                        to="contas_receber.contareceber",
                    ),
                ),
                (
                    "forma_pgto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="formas_pgto.formapgto",
                    ),
                ),
                (
                    "vinc_emp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forma de pagamento da baixa",
                "verbose_name_plural": "Formas de pagamento da baixa",
            },
        ),
    ]
