# Generated by Django 4.1.13 on 2026-04-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas_receber", "0006_contareceberbaixaforma"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contareceber",
            name="num_conta",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Nº Conta"
            ),
        ),
    ]
