# Generated by Django 4.1.13 on 2026-04-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_receber', '0007_alter_contareceber_num_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='obs_internas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='data_emissao',
            field=models.DateField(),
        ),
    ]
