# Generated by Django 4.1.13 on 2026-05-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_receber', '0008_contareceber_obs_internas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
