# Generated by Django 4.1.13 on 2026-05-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_receber', '0009_contareceber_codigo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contareceber',
            constraint=models.UniqueConstraint(fields=('codigo', 'vinc_emp'), name='unique_codigo_conta_receber_empresa'),
        ),
    ]
