# Generated by Django 4.1.13 on 2026-07-01 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas_receber', '0010_contareceber_unique_codigo_conta_receber_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='tipo',
            field=models.CharField(choices=[('Original', 'Original'), ('Remanescente', 'Remanescente')], default='Original', max_length=15),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='titulo_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titulos_remanescentes', to='contas_receber.contareceber'),
        ),
    ]
