# Generated by Django 4.1.13 on 2026-04-28 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formas_pgto', '0006_formapgto_forma_padrao'),
        ('filiais', '0017_filial_multi_m2'),
        ('pdvs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresas', '0009_empresa_senha_portal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('Aberto', 'Aberto'), ('Fechado', 'Fechado')], default='Aberto', max_length=10)),
                ('observacao', models.TextField(blank=True)),
                ('saldo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diferenca', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pdvs.pdv')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vinc_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('vinc_fil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filiais.filial')),
            ],
        ),
        migrations.CreateModel(
            name='CaixaMovimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saída')], max_length=10)),
                ('categoria', models.CharField(choices=[('Venda', 'Venda'), ('Sangria', 'Sangria'), ('Suprimento', 'Suprimento'), ('Saldo Inicial', 'Saldo Inicial')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='lancpdvs.caixa')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formas_pgto.formapgto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaixaFechamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_registrado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_informado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diferenca', models.DecimalField(decimal_places=2, max_digits=10)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lancpdvs.caixa')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formas_pgto.formapgto')),
            ],
        ),
        migrations.AddIndex(
            model_name='caixamovimento',
            index=models.Index(fields=['caixa', 'tipo'], name='lancpdvs_ca_caixa_i_2abb0a_idx'),
        ),
        migrations.AddIndex(
            model_name='caixamovimento',
            index=models.Index(fields=['caixa', 'forma_pagamento'], name='lancpdvs_ca_caixa_i_bc1e15_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='caixafechamento',
            unique_together={('caixa', 'forma_pagamento')},
        ),
    ]
