# Generated by Django 4.1.13 on 2026-07-15 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formas_pgto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(blank=True, null=True)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('Aberto', 'Aberto'), ('Fechado', 'Fechado')], default='Aberto', max_length=10)),
                ('observacao', models.TextField(blank=True)),
                ('saldo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diferenca', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Lançamento de Caixas',
                'permissions': [('caixa_outro_user', 'Pode realizar lançamentos em caixas de outros usuários')],
            },
        ),
        migrations.CreateModel(
            name='CaixaFechamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_registrado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_informado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diferenca', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CaixaMovimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('Ativo', 'Ativo'), ('Cancelado', 'Cancelado')], default='Ativo', max_length=10)),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saída')], max_length=10)),
                ('categoria', models.CharField(choices=[('Venda', 'Venda'), ('Devolução', 'Devolução'), ('Troca', 'Troca'), ('Sangria', 'Sangria'), ('Suprimento', 'Suprimento'), ('Saldo Inicial', 'Saldo Inicial')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='lancpdvs.caixa')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formas_pgto.formapgto')),
            ],
        ),
    ]
