# Generated by Django 4.1.13 on 2026-04-29 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_remove_pagamento_pedido_remove_pagamento_pedido_ref_and_more'),
        ('lancpdvs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixamovimento',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.pedido'),
        ),
    ]
