# Generated by Django 4.1.13 on 2026-07-15 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formas_pgto', '0001_initial'),
        ('lancpdvs', '0001_initial'),
        ('pdvs', '0001_initial'),
        ('pedidos', '0001_initial'),
        ('filiais', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixamovimento',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='caixamovimento',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caixafechamento',
            name='caixa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechamentos', to='lancpdvs.caixa'),
        ),
        migrations.AddField(
            model_name='caixafechamento',
            name='forma_pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formas_pgto.formapgto'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pdvs.pdv'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caixa',
            name='vinc_emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='vinc_fil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filiais.filial'),
        ),
        migrations.AddIndex(
            model_name='caixamovimento',
            index=models.Index(fields=['caixa', 'tipo'], name='lancpdvs_ca_caixa_i_2abb0a_idx'),
        ),
        migrations.AddIndex(
            model_name='caixamovimento',
            index=models.Index(fields=['caixa', 'forma_pagamento'], name='lancpdvs_ca_caixa_i_bc1e15_idx'),
        ),
        migrations.AddConstraint(
            model_name='caixamovimento',
            constraint=models.UniqueConstraint(fields=('caixa', 'codigo'), name='unique_codigo_movimento_caixa'),
        ),
        migrations.AlterUniqueTogether(
            name='caixafechamento',
            unique_together={('caixa', 'forma_pagamento')},
        ),
        migrations.AddConstraint(
            model_name='caixa',
            constraint=models.UniqueConstraint(fields=('codigo', 'vinc_emp'), name='unique_codigo_caixa_empresa'),
        ),
    ]
