# Generated by Django 4.1.13 on 2026-05-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancpdvs', '0003_caixa_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caixa',
            options={'verbose_name_plural': 'Lançamento de Caixas'},
        ),
        migrations.AddConstraint(
            model_name='caixa',
            constraint=models.UniqueConstraint(fields=('codigo', 'vinc_emp'), name='unique_codigo_caixa_empresa'),
        ),
    ]
