# Generated by Django 4.1.13 on 2026-06-21 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lancpdvs', '0004_alter_caixa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixafechamento',
            name='caixa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechamentos', to='lancpdvs.caixa'),
        ),
    ]
