# Generated by Django 4.1.13 on 2026-06-21 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lancpdvs', '0005_alter_caixafechamento_caixa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caixa',
            options={'permissions': [('caixa_outro_user', 'Pode realizar lançamentos em caixas de outros usuários')], 'verbose_name_plural': 'Lançamento de Caixas'},
        ),
    ]
