# Generated by Django 4.1.13 on 2026-07-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lancpdvs", "0006_alter_caixa_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="caixamovimento",
            name="codigo",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="caixamovimento",
            constraint=models.UniqueConstraint(
                fields=("caixa", "codigo"), name="unique_codigo_movimento_caixa"
            ),
        ),
    ]
