# Generated by Django 4.1.13 on 2026-07-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lancpdvs", "0007_caixamovimento_codigo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="caixamovimento",
            name="situacao",
            field=models.CharField(
                choices=[("Ativo", "Ativo"), ("Cancelado", "Cancelado")],
                default="Ativo",
                max_length=10,
            ),
        ),
    ]
