# Generated by Django 4.1.13 on 2026-07-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancpdvs', '0008_caixamovimento_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixamovimento',
            name='categoria',
            field=models.CharField(choices=[('Venda', 'Venda'), ('Devolução', 'Devolução'), ('Troca', 'Troca'), ('Sangria', 'Sangria'), ('Suprimento', 'Suprimento'), ('Saldo Inicial', 'Saldo Inicial')], max_length=20),
        ),
    ]
