# Generated by Django 4.1.13 on 2026-05-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0004_grupo_codigo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='grupo',
            constraint=models.UniqueConstraint(fields=('nome_grupo', 'vinc_emp'), name='unique_nome_grupo_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='grupo',
            constraint=models.UniqueConstraint(fields=('codigo', 'vinc_emp'), name='unique_codigo_grupo_empresa'),
        ),
    ]
