# Generated by Django 4.1.13 on 2026-05-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0004_alter_cidade_nome_cidade_alter_cidade_vinc_emp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
