# Generated by Django 4.1.13 on 2026-05-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0005_cidade_codigo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cidade',
            constraint=models.UniqueConstraint(fields=('codigo', 'vinc_emp'), name='unique_codigo_cidade_empresa'),
        ),
    ]
