# Generated by Django 4.1.13 on 2025-09-25 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fornecedores", "0001_initial"),
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numeracao", models.CharField(max_length=25)),
                ("dt_emi", models.DateField(blank=True, null=True)),
                ("dt_ent", models.DateField(blank=True, null=True)),
                (
                    "tp_frete",
                    models.CharField(
                        choices=[("CIF", "CIF"), ("FOB", "FOB")],
                        default="CIF",
                        max_length=3,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("Pedido", "Pedido"), ("Nota Fiscal", "Nota Fiscal")],
                        max_length=12,
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Efetivada", "Efetivada"),
                            ("Cancelada", "Cancelada"),
                        ],
                        default="Pendente",
                        max_length=10,
                    ),
                ),
                ("modelo", models.CharField(blank=True, max_length=2, null=True)),
                ("serie", models.CharField(blank=True, max_length=2, null=True)),
                ("nat_op", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "chave_acesso",
                    models.CharField(blank=True, max_length=44, null=True),
                ),
                ("obs", models.TextField(blank=True, default="")),
                (
                    "frete",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("motivo", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fornecedores.fornecedor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Entradas de NF/Pedidos",
                "permissions": [
                    ("efetivar_entrada", "Pode efetivar entrada de notas/pedidos"),
                    ("cancelar_entrada", "Pode cancelar entrada de notas/pedidos"),
                ],
            },
        ),
        migrations.CreateModel(
            name="EntradaProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=2, max_digits=10)),
                ("desconto", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "entrada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="entradas.entrada",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produtos_vinculados",
                        to="produtos.produto",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="entradaproduto",
            constraint=models.UniqueConstraint(
                fields=("entrada", "produto"), name="uniq_conf_relacao"
            ),
        ),
    ]
