# Generated by Django 4.1.13 on 2026-07-15 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filiais', '0001_initial'),
        ('entradas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='vinc_fil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filiais.filial'),
        ),
        migrations.AddConstraint(
            model_name='entradaproduto',
            constraint=models.UniqueConstraint(fields=('entrada', 'produto'), name='uniq_conf_relacao'),
        ),
        migrations.AddConstraint(
            model_name='entrada',
            constraint=models.UniqueConstraint(fields=('codigo', 'vinc_emp'), name='unique_codigo_entrada_empresa'),
        ),
    ]
