# Generated by Django 4.1.13 on 2026-08-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='xml_nfe',
            field=models.FileField(blank=True, null=True, upload_to='entradas/xml/%Y/%m/', verbose_name='XML NF-e'),
        ),
    ]
