# Generated by Django 4.1.13 on 2026-03-15 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fornecedores", "0003_alter_fornecedor_vinc_emp"),
        ("filiais", "0011_alter_filial_dt_criacao_alter_filial_dt_inativacao"),
        ("entradas", "0003_entrada_vinc_fil_alter_entrada_vinc_emp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entrada",
            name="fornecedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="fornecedores.fornecedor",
            ),
        ),
        migrations.AlterField(
            model_name="entrada",
            name="vinc_fil",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="filiais.filial",
            ),
        ),
    ]
