# Generated by Django 4.1.13 on 2026-08-05 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0003_entrada_xml_nfe'),
    ]

    operations = [
        migrations.CreateModel(
            name='CobrancaEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('numero', models.CharField(blank=True, max_length=30)),
                ('vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas', to='entradas.entrada')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('entrada', 'ordem')},
            },
        ),
    ]
