# Generated by Django 4.1.13 on 2026-08-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0004_cobrancaentrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrancaentrada',
            name='tp_conta',
            field=models.CharField(blank=True, max_length=30, verbose_name='Tipo de Conta'),
        ),
    ]
