# Generated by Django 4.1.13 on 2026-03-23 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tabelas_preco", "0005_alter_tabelapreco_descricao_and_more"),
        ("entradas", "0004_alter_entrada_fornecedor_alter_entrada_vinc_fil"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntradaProdutoTabela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "margem",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "valor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "entrada_produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tabelas",
                        to="entradas.entradaproduto",
                    ),
                ),
                (
                    "tabela_preco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tabelas_preco.tabelapreco",
                    ),
                ),
            ],
        ),
    ]
