# Generated by Django 4.1.13 on 2026-05-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0005_entradaprodutotabela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='serie',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
