# Generated by Django 4.1.13 on 2026-08-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0005_cobrancaentrada_tp_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='dt_efet',
            field=models.DateField(blank=True, null=True),
        ),
    ]
