# Generated by Django 4.1.13 on 2026-08-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0006_entrada_dt_efet'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrancaentrada',
            name='num_tp_conta',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
