# Generated by Django 4.1.13 on 2026-05-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0006_alter_entrada_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
