# Generated by Django 4.1.13 on 2026-02-16 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0009_empresa_senha_portal"),
        ("marcas", "0002_alter_marca_vinc_emp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marca",
            name="nome_marca",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="marca",
            name="vinc_emp",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="empresas.empresa",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="marca",
            unique_together={("nome_marca", "vinc_emp")},
        ),
    ]
