# Generated by Django 4.1.13 on 2026-05-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcas', '0003_alter_marca_nome_marca_alter_marca_vinc_emp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
