# Generated by Django 4.1.13 on 2026-05-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcas', '0004_marca_codigo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marca',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='marca',
            constraint=models.UniqueConstraint(fields=('nome_marca', 'vinc_emp'), name='unique_nome_marca_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='marca',
            constraint=models.UniqueConstraint(fields=('codigo', 'vinc_emp'), name='unique_codigo_marca_empresa'),
        ),
    ]
