# Generated by Django 4.1.13 on 2025-09-25 16:39

from django.db import migrations, models
import django.db.models.deletion
import tecnicos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bairros", "0001_initial"),
        ("cidades", "0001_initial"),
        ("estados", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tecnico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[("Ativo", "Ativo"), ("Inativo", "Inativo")],
                        max_length=10,
                        verbose_name="Situação",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("endereco", models.CharField(max_length=100)),
                ("cep", models.CharField(max_length=10)),
                ("numero", models.CharField(max_length=10)),
                ("tel", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=40)),
                (
                    "dt_reg",
                    models.CharField(
                        default=tecnicos.models.data_hoje_formatada,
                        max_length=30,
                        verbose_name="Data de Registro",
                    ),
                ),
                (
                    "bairro",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bairros.bairro",
                    ),
                ),
                (
                    "cidade",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cidades.cidade",
                    ),
                ),
                (
                    "uf",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="estados.estado",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Técnicos",
            },
        ),
    ]
