# Generated by Django 4.1.13 on 2025-09-25 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("filiais", "0002_rename_bairro_filial_bairro_fil_and_more"),
        ("tecnicos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tecnico",
            name="vinc_emp",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="filiais.filial",
            ),
            preserve_default=False,
        ),
    ]
