# Generated by Django 4.1.13 on 2026-03-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tecnicos", "0003_alter_tecnico_vinc_emp"),
    ]

    operations = [
        migrations.AddField(
            model_name="tecnico",
            name="dt_reg_data",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="Data de Registro"
            ),
        ),
    ]
