# Generated by Django 4.1.13 on 2026-03-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tecnicos", "0004_tecnico_dt_reg_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tecnico",
            name="dt_reg_data",
        ),
        migrations.AlterField(
            model_name="tecnico",
            name="dt_reg",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="Data de Registro"
            ),
        ),
    ]
