# Generated by Django 4.1.13 on 2026-05-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0005_remove_tecnico_dt_reg_data_alter_tecnico_dt_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
