# Generated by Django 4.1.13 on 2026-07-15 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=10, verbose_name='Situação')),
                ('pessoa', models.CharField(choices=[('Física', 'Física'), ('Jurídica', 'Jurídica')], max_length=10, verbose_name='Pessoa')),
                ('somente_avista', models.BooleanField(default=False, verbose_name='Vender apenas à vista')),
                ('cpf_cnpj', models.CharField(max_length=25)),
                ('ie', models.CharField(blank=True, max_length=20, null=True)),
                ('razao_social', models.CharField(max_length=100)),
                ('fantasia', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=10)),
                ('complem', models.CharField(blank=True, default='', max_length=30)),
                ('avulso', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=10, verbose_name='Situação')),
                ('tel', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('dt_reg', models.DateField(blank=True, db_index=True, null=True, verbose_name='Data de Registro')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='CreditoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('situacao', models.CharField(choices=[('Aberto', 'Aberto'), ('Utilizado', 'Utilizado'), ('Cancelado', 'Cancelado')], default='Aberto', max_length=10)),
                ('observacao', models.TextField(blank=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Crédito de Cliente',
                'verbose_name_plural': 'Créditos de Clientes',
                'ordering': ['-data'],
            },
        ),
    ]
