# Generated by Django 4.1.13 on 2025-09-25 16:34

import clientes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("estados", "0001_initial"),
        ("cidades", "0001_initial"),
        ("bairros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[("Ativo", "Ativo"), ("Inativo", "Inativo")],
                        max_length=10,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "pessoa",
                    models.CharField(
                        choices=[("Física", "Física"), ("Jurídica", "Jurídica")],
                        max_length=10,
                        verbose_name="Pessoa",
                    ),
                ),
                ("cpf_cnpj", models.CharField(max_length=25)),
                ("ie", models.CharField(blank=True, max_length=20, null=True)),
                ("razao_social", models.CharField(max_length=100)),
                ("fantasia", models.CharField(max_length=100)),
                ("endereco", models.CharField(max_length=100)),
                ("cep", models.CharField(max_length=10)),
                ("numero", models.CharField(max_length=10)),
                ("complem", models.CharField(blank=True, default="", max_length=30)),
                ("tel", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=40)),
                (
                    "dt_reg",
                    models.CharField(
                        default=clientes.models.data_hoje_formatada,
                        max_length=10,
                        verbose_name="Data de Registro",
                    ),
                ),
                (
                    "bairro",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bairros.bairro",
                    ),
                ),
                (
                    "cidade",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cidades.cidade",
                    ),
                ),
                (
                    "uf",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="estados.estado",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Clientes",
            },
        ),
    ]
