# Generated by Django 4.1.13 on 2026-07-15 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
        ('bairros', '0001_initial'),
        ('cidades', '0001_initial'),
        ('pedidos', '0001_initial'),
        ('filiais', '0001_initial'),
        ('empresas', '0001_initial'),
        ('estados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditocliente',
            name='pedido_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditos_gerados', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='creditocliente',
            name='pedido_utilizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creditos_utilizados', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='creditocliente',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditocliente',
            name='vinc_emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='creditocliente',
            name='vinc_fil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filiais.filial'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bairros.bairro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cidades.cidade'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='uf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estados.estado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='vinc_emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='vinc_fil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filiais.filial'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('cpf_cnpj', 'vinc_emp'), name='unique_cpf_cnpj_cliente_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('codigo', 'vinc_emp'), name='unique_codigo_cliente_empresa'),
        ),
    ]
