# Generated by Django 4.1.13 on 2026-03-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0003_alter_cliente_vinc_emp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="dt_reg",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="Data de Registro"
            ),
        ),
        migrations.AddConstraint(
            model_name="cliente",
            constraint=models.UniqueConstraint(
                fields=("cpf_cnpj", "vinc_emp"), name="unique_cpf_cnpj_por_empresa"
            ),
        ),
    ]
