# Generated by Django 4.1.13 on 2026-03-31 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("filiais", "0014_filial_tb_preco"),
        ("clientes", "0004_alter_cliente_dt_reg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="vinc_fil",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="filiais.filial",
            ),
        ),
    ]
