# Generated by Django 4.1.13 on 2026-05-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_vinc_fil'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='somente_avista',
            field=models.BooleanField(default=False, verbose_name='Vender apenas à vista'),
        ),
    ]
