# Generated by Django 4.1.13 on 2026-05-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_cliente_somente_avista'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
