# Generated by Django 4.1.13 on 2026-05-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_cliente_codigo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cliente',
            name='unique_cpf_cnpj_por_empresa',
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('cpf_cnpj', 'vinc_emp'), name='unique_cpf_cnpj_cliente_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('codigo', 'vinc_emp'), name='unique_codigo_cliente_empresa'),
        ),
    ]
