# Generated by Django 4.1.13 on 2026-07-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0008_remove_cliente_unique_cpf_cnpj_por_empresa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="avulso",
            field=models.CharField(
                choices=[("Sim", "Sim"), ("Não", "Não")],
                default="Não",
                max_length=10,
                verbose_name="Situação",
            ),
        ),
    ]
