# Generated by Django 4.1.13 on 2026-07-09 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0024_pedido_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresas', '0009_empresa_senha_portal'),
        ('filiais', '0030_filial_imp_recibo_cr'),
        ('clientes', '0009_cliente_avulso'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('situacao', models.CharField(choices=[('Aberto', 'Aberto'), ('Utilizado', 'Utilizado'), ('Cancelado', 'Cancelado')], default='Aberto', max_length=10)),
                ('observacao', models.TextField(blank=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditos', to='clientes.cliente')),
                ('pedido_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditos_gerados', to='pedidos.pedido')),
                ('pedido_utilizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creditos_utilizados', to='pedidos.pedido')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vinc_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('vinc_fil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filiais.filial')),
            ],
            options={
                'verbose_name': 'Crédito de Cliente',
                'verbose_name_plural': 'Créditos de Clientes',
                'ordering': ['-data'],
            },
        ),
    ]
