# Generated by Django 4.1.13 on 2026-04-28 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0009_empresa_senha_portal'),
        ('filiais', '0017_filial_multi_m2'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('situacao', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=10)),
                ('vinc_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('vinc_fil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filiais.filial')),
            ],
        ),
    ]
