# Generated by Django 4.1.13 on 2026-05-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdvs', '0002_pdv_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdv',
            options={'verbose_name_plural': 'Pontos de Venda'},
        ),
        migrations.AddConstraint(
            model_name='pdv',
            constraint=models.UniqueConstraint(fields=('codigo', 'vinc_emp'), name='unique_codigo_pdv_empresa'),
        ),
    ]
