# Generated by Django 4.1.13 on 2025-09-28 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("filiais", "0005_remove_filial_qtd_filial_remove_filial_qtd_usuarios"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormaPgto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=100, unique=True)),
                (
                    "situacao",
                    models.CharField(
                        choices=[("Ativo", "Ativo"), ("Inativo", "Inativo")],
                        max_length=7,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "troco",
                    models.CharField(
                        choices=[("Sim", "Sim"), ("Não", "Não")],
                        max_length=3,
                        verbose_name="Permite troco?",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("A vista", "A vista"), ("A prazo", "A prazo")],
                        max_length=8,
                        verbose_name="Tipo da Forma",
                    ),
                ),
                (
                    "vinc_emp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="filiais.filial",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Formas de Pagamento",
            },
        ),
    ]
