# Generated by Django 4.1.13 on 2026-07-15 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPgto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(blank=True, null=True)),
                ('descricao', models.CharField(max_length=100)),
                ('situacao', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=7)),
                ('troco', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3)),
                ('forma_padrao', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3)),
                ('tipo', models.CharField(choices=[('A vista', 'A vista'), ('A prazo', 'A prazo')], default='A vista', max_length=8)),
                ('gera_parcelas', models.BooleanField(default=False)),
                ('gateway', models.CharField(choices=[('nenhum', 'Nenhum'), ('mercadopago', 'Mercado Pago'), ('pagseguro', 'PagSeguro'), ('stripe', 'Stripe'), ('pix_direto', 'Pix Direto'), ('infinitepay', 'InfinitePay')], default='nenhum', max_length=20)),
                ('credenciais', models.JSONField(blank=True, null=True)),
                ('vinc_emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
            options={
                'verbose_name_plural': 'Formas de Pagamento',
            },
        ),
        migrations.AddConstraint(
            model_name='formapgto',
            constraint=models.UniqueConstraint(fields=('codigo', 'vinc_emp'), name='unique_codigo_formas_empresa'),
        ),
    ]
