# Generated by Django 4.1.13 on 2026-02-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formas_pgto", "0002_alter_formapgto_vinc_emp"),
    ]

    operations = [
        migrations.AddField(
            model_name="formapgto",
            name="gera_parcelas",
            field=models.BooleanField(default=False),
        ),
    ]
