# Generated by Django 4.1.13 on 2026-02-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formas_pgto", "0003_formapgto_gera_parcelas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formapgto",
            name="troco",
            field=models.CharField(
                choices=[("Sim", "Sim"), ("Não", "Não")],
                default="Não",
                max_length=3,
                verbose_name="Permite troco?",
            ),
        ),
    ]
