# Generated by Django 4.1.13 on 2026-04-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formas_pgto', '0004_alter_formapgto_troco'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapgto',
            name='credenciais',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formapgto',
            name='gateway',
            field=models.CharField(choices=[('nenhum', 'Nenhum'), ('mercadopago', 'Mercado Pago'), ('pagseguro', 'PagSeguro'), ('stripe', 'Stripe'), ('pix_direto', 'Pix Direto')], default='nenhum', max_length=20),
        ),
        migrations.AlterField(
            model_name='formapgto',
            name='situacao',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=7),
        ),
        migrations.AlterField(
            model_name='formapgto',
            name='tipo',
            field=models.CharField(choices=[('A vista', 'A vista'), ('A prazo', 'A prazo')], max_length=8),
        ),
        migrations.AlterField(
            model_name='formapgto',
            name='troco',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
    ]
