# Generated by Django 4.1.13 on 2026-04-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formas_pgto', '0005_formapgto_credenciais_formapgto_gateway_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapgto',
            name='forma_padrao',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
    ]
