# Generated by Django 4.1.13 on 2026-05-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formas_pgto', '0006_formapgto_forma_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapgto',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
