# Generated by Django 4.1.13 on 2026-05-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formas_pgto", "0008_formapgto_unique_codigo_formas_empresa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formapgto",
            name="descricao",
            field=models.CharField(max_length=100),
        ),
    ]
