# Generated by Django 4.1.13 on 2026-05-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formas_pgto", "0009_alter_formapgto_descricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formapgto",
            name="gateway",
            field=models.CharField(
                choices=[
                    ("nenhum", "Nenhum"),
                    ("mercadopago", "Mercado Pago"),
                    ("pagseguro", "PagSeguro"),
                    ("stripe", "Stripe"),
                    ("pix_direto", "Pix Direto"),
                    ("infinitepay", "InfinitePay"),
                ],
                default="nenhum",
                max_length=20,
            ),
        ),
    ]
