# Generated by Django 4.1.13 on 2026-06-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formas_pgto', '0010_alter_formapgto_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapgto',
            name='tipo',
            field=models.CharField(choices=[('A vista', 'A vista'), ('A prazo', 'A prazo')], default='A vista', max_length=8),
        ),
    ]
