# Generated by Django 4.1.13 on 2025-09-25 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("tecnicos", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orcamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fantasia_emp", models.CharField(blank=True, max_length=255)),
                ("nome_cli", models.CharField(blank=True, max_length=255)),
                ("nome_solicitante", models.CharField(blank=True, max_length=255)),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("Aberto", "Aberto"),
                            ("Faturado", "Faturado"),
                            ("Cancelado", "Cancelado"),
                        ],
                        default="Aberto",
                        max_length=10,
                    ),
                ),
                ("num_orcamento", models.CharField(max_length=25)),
                ("obs_cli", models.TextField(blank=True, default="")),
                ("qtd", models.CharField(max_length=1000)),
                (
                    "tp_lamina",
                    models.CharField(
                        choices=[
                            ("Fechada", "Fechada"),
                            ("Transvision", "Transvision"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "tp_vao",
                    models.CharField(
                        choices=[
                            ("Dentro do Vão", "Dentro do Vão"),
                            ("Fora do Vão", "Fora do Vão"),
                        ],
                        max_length=50,
                    ),
                ),
                ("larg", models.CharField(max_length=1000)),
                ("alt", models.CharField(max_length=1000)),
                (
                    "pintura",
                    models.CharField(
                        choices=[("Sim", "Sim"), ("Não", "Não")], max_length=5
                    ),
                ),
                (
                    "cor",
                    models.CharField(
                        choices=[
                            ("Preto", "Preto"),
                            ("Branco", "Branco"),
                            ("Amarelo", "Amarelo"),
                            ("Vermelho", "Vermelho"),
                            ("Roxo Açaí", "Roxo Açaí"),
                            ("Azul Pepsi", "Azul Pepsi"),
                            ("Azul Claro", "Azul Claro"),
                            ("Cinza Claro", "Cinza Claro"),
                            ("Cinza Grafite", "Cinza Grafite"),
                            ("Verde", "Verde"),
                        ],
                        max_length=30,
                    ),
                ),
                ("fator_peso", models.CharField(max_length=1000)),
                ("peso", models.CharField(max_length=1000)),
                ("eixo_motor", models.CharField(max_length=1000)),
                ("larg_corte", models.CharField(max_length=1000)),
                ("alt_corte", models.CharField(max_length=1000)),
                ("rolo", models.CharField(max_length=1000)),
                ("m2", models.CharField(max_length=1000)),
                ("produtos", models.JSONField(default=list)),
                ("adicionais", models.JSONField(default=list)),
                ("formas_pgto", models.JSONField(default=list)),
                ("obs_form_pgto", models.TextField(blank=True, default="")),
                ("subtotal", models.CharField(max_length=1000)),
                (
                    "desconto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "acrescimo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total", models.CharField(max_length=1000)),
                ("dt_emi", models.DateField(blank=True, null=True)),
                ("dt_ent", models.DateField(blank=True, null=True)),
                ("motivo", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "cli",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clientes.cliente",
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tecnicos.tecnico",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Orçamentos",
                "permissions": [
                    ("faturar_orcamento", "Pode faturar orçamento"),
                    ("cancelar_orcamento", "Pode cancelar orçamento"),
                ],
            },
        ),
    ]
