# Generated by Django 4.1.13 on 2026-07-15 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
        ('tecnicos', '0001_initial'),
        ('formas_pgto', '0001_initial'),
        ('produtos', '0001_initial'),
        ('tabelas_preco', '0001_initial'),
        ('filiais', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(blank=True, null=True)),
                ('fantasia_emp', models.CharField(blank=True, max_length=255)),
                ('nome_cli', models.CharField(blank=True, max_length=255)),
                ('nome_solicitante', models.CharField(blank=True, max_length=255)),
                ('nome_fornecedor', models.CharField(blank=True, max_length=255)),
                ('situacao', models.CharField(choices=[('Aberto', 'Aberto'), ('Faturado', 'Faturado'), ('Cancelado', 'Cancelado')], db_index=True, default='Aberto', max_length=10)),
                ('status', models.CharField(choices=[('Em Produção', 'Em Produção'), ('Embalada', 'Embalada'), ('Entregue', 'Entregue'), ('Instalada', 'Instalada')], db_index=True, default='Em Produção', max_length=15)),
                ('status_pagamento', models.CharField(choices=[('Pendente', 'Pendente'), ('Parcial', 'Parcial'), ('Pago', 'Pago')], db_index=True, default='Pendente', max_length=15)),
                ('num_orcamento', models.CharField(db_index=True, max_length=25)),
                ('obs_cli', models.TextField(blank=True, default='')),
                ('pintura', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=5)),
                ('portao_social', models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=5)),
                ('lg_ps', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('at_ps', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('vl_p_s', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('tp_pintura', models.CharField(choices=[('Eletrostática', 'Eletrostática'), ('Automotiva', 'Automotiva')], default='Eletrostática', max_length=13)),
                ('cor', models.CharField(choices=[('', ''), ('Preto', 'Preto'), ('Branco', 'Branco'), ('Amarelo', 'Amarelo'), ('Vermelho', 'Vermelho'), ('Roxo Açaí', 'Roxo Açaí'), ('Azul Pepsi', 'Azul Pepsi'), ('Azul Claro', 'Azul Claro'), ('Cinza Claro', 'Cinza Claro'), ('Cinza Grafite', 'Cinza Grafite'), ('Cinza Chumbo', 'Cinza Chumbo'), ('Chumbo', 'Chumbo'), ('Verde', 'Verde'), ('Bege', 'Bege'), ('Bege Areia', 'Bege Areia'), ('Marrom', 'Marrom'), ('Marrom Café', 'Marrom Café'), ('Laranja', 'Laranja'), ('Azul Royal', 'Azul Royal'), ('Azul Marinho', 'Azul Marinho'), ('Azul Pepsi', 'Azul Pepsi'), ('Verde Musgo', 'Verde Musgo'), ('Verde Bandeira', 'Verde Bandeira'), ('Vinho', 'Vinho'), ('Prata', 'Prata')], default='Preto', max_length=30)),
                ('obs_form_pgto', models.TextField(blank=True, default='')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('acrescimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dt_emi', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('dt_fat', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('dt_ent', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=60, null=True)),
                ('cli', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.fornecedor')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tecnicos.tecnico')),
                ('tabela_preco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tabelas_preco.tabelapreco')),
                ('vinc_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('vinc_fil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='filiais.filial')),
            ],
            options={
                'verbose_name_plural': 'Orçamentos',
                'permissions': [('clonar_orcamento', 'Pode clonar orçamento'), ('faturar_orcamento', 'Pode faturar orçamento'), ('cancelar_orcamento', 'Pode cancelar orçamento'), ('atribuir_desconto', 'Pode atribuir descontos em orçamento'), ('atribuir_acrescimo', 'Pode atribuir acréscimo em orçamento'), ('alterar_dt_venc_orc', 'Pode alterar a data de vencimento na fatura de orçamento'), ('alterar_dt_fat_orc', 'Pode alterar a data de faturamento na fatura de orçamento'), ('vender_sem_estoque_orc', 'Pode vender sem estoque em orçamentos')],
            },
        ),
        migrations.CreateModel(
            name='PortaOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1)),
                ('largura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qtd_lam', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('m2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('larg_corte', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('alt_corte', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rolo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('peso', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('fator_peso', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('eixo_motor', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('tp_lamina', models.CharField(choices=[('Fechada', 'Fechada'), ('Transvision', 'Transvision')], default='Fechada', max_length=25)),
                ('tp_vao', models.CharField(choices=[('Dentro do Vão', 'Dentro do Vão'), ('Fora do Vão', 'Fora do Vão'), ('1 Lado Dentro do Vão', '1 Lado Dentro do Vão')], default='Fora do Vão', max_length=50)),
                ('op_guia_e', models.CharField(choices=[('Dentro do Vão', 'Dentro do Vão'), ('Fora do Vão', 'Fora do Vão')], default='Dentro do Vão', max_length=13, verbose_name='Opção Guia Esquerdo')),
                ('op_guia_d', models.CharField(choices=[('Dentro do Vão', 'Dentro do Vão'), ('Fora do Vão', 'Fora do Vão')], default='Dentro do Vão', max_length=13, verbose_name='Opção Guia Direito')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portas', to='orcamentos.orcamento')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoPermissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(blank=True, null=True)),
                ('acao', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovada', 'Aprovada'), ('Negada', 'Negada'), ('Expirada', 'Expirada')], default='Pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('vinc_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_permissao', to='empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='PortaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('regra_origem', models.CharField(blank=True, max_length=50, null=True)),
                ('porta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='orcamentos.portaorcamento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portas_produtos', to='produtos.produto')),
            ],
        ),
        migrations.CreateModel(
            name='PortaAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('regra_origem', models.CharField(blank=True, max_length=50, null=True)),
                ('lado', models.CharField(blank=True, choices=[('', '---------'), ('E', 'Esquerdo'), ('D', 'Direito'), ('C', 'Centro')], default='', max_length=1)),
                ('porta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adicionais', to='orcamentos.portaorcamento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portas_adicionais', to='produtos.produto')),
            ],
        ),
        migrations.CreateModel(
            name='OrcamentoFormaPgto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('parcelas', models.PositiveIntegerField(default=1)),
                ('dias_intervalo', models.PositiveIntegerField(default=0)),
                ('formas_pgto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='formas_pgto.formapgto')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas_pgto', to='orcamentos.orcamento')),
            ],
        ),
        migrations.AddConstraint(
            model_name='orcamentoformapgto',
            constraint=models.UniqueConstraint(fields=('orcamento', 'formas_pgto'), name='uniq_orc_formapgto'),
        ),
        migrations.AddConstraint(
            model_name='orcamento',
            constraint=models.UniqueConstraint(fields=('codigo', 'vinc_emp'), name='unique_codigo_orcamento_empresa'),
        ),
    ]
