# Generated by Django 4.1.13 on 2026-07-18 23:16

from django.db import migrations, models
import orcamentos.models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='dt_prev_instalacao',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Dt. Prevista Instalação'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='prioridade',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Alta', 'Alta'), ('Urgente', 'Urgente')], db_index=True, default='Normal', max_length=15, verbose_name='Prioridade'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='tipo_entrega',
            field=models.CharField(choices=[('Retirada', 'Retirada'), ('Entrega', 'Entrega'), ('Entrega e Instalação', 'Entrega e Instalação')], db_index=True, default='Retirada', max_length=25, verbose_name='Tipo de Entrega'),
        ),
        migrations.AddField(
            model_name='portaorcamento',
            name='acabamento_guia',
            field=models.CharField(choices=[('Sem Acabamento', 'Sem Acabamento'), ('Com Acabamento', 'Com Acabamento'), ('Acabamento Especial', 'Acabamento Especial')], default='Sem Acabamento', max_length=25, verbose_name='Acabamento Guia'),
        ),
        migrations.AddField(
            model_name='portaorcamento',
            name='altura_passagem',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Altura Passagem'),
        ),
        migrations.AddField(
            model_name='portaorcamento',
            name='cor_porta',
            field=models.CharField(choices=[('', ''), ('Preto', 'Preto'), ('Branco', 'Branco'), ('Amarelo', 'Amarelo'), ('Vermelho', 'Vermelho'), ('Roxo Açaí', 'Roxo Açaí'), ('Azul Pepsi', 'Azul Pepsi'), ('Azul Claro', 'Azul Claro'), ('Cinza Claro', 'Cinza Claro'), ('Cinza Grafite', 'Cinza Grafite'), ('Cinza Chumbo', 'Cinza Chumbo'), ('Chumbo', 'Chumbo'), ('Verde', 'Verde'), ('Bege', 'Bege'), ('Bege Areia', 'Bege Areia'), ('Marrom', 'Marrom'), ('Marrom Café', 'Marrom Café'), ('Laranja', 'Laranja'), ('Azul Royal', 'Azul Royal'), ('Azul Marinho', 'Azul Marinho'), ('Verde Musgo', 'Verde Musgo'), ('Verde Bandeira', 'Verde Bandeira'), ('Vinho', 'Vinho'), ('Prata', 'Prata')], default='Preto', max_length=30, verbose_name='Cor da Porta'),
        ),
        migrations.AddField(
            model_name='portaorcamento',
            name='foto_vao',
            field=models.ImageField(blank=True, null=True, upload_to=orcamentos.models.caminho_foto_vao_orcamento, verbose_name='Foto do Vão'),
        ),
        migrations.AddField(
            model_name='portaorcamento',
            name='garantia_motor_meses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portaorcamento',
            name='lado_motor',
            field=models.CharField(choices=[('Esquerdo', 'Esquerdo'), ('Direito', 'Direito'), ('Central', 'Central')], default='Esquerdo', max_length=25, verbose_name='Lado do Motor'),
        ),
        migrations.AddField(
            model_name='portaorcamento',
            name='largura_passagem',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Largura Passagem'),
        ),
        migrations.AddField(
            model_name='portaorcamento',
            name='nr_serie_motor',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nº Série Motor'),
        ),
        migrations.AddField(
            model_name='portaorcamento',
            name='obs_porta',
            field=models.TextField(blank=True, default='', verbose_name='Obs. Porta'),
        ),
        migrations.AddField(
            model_name='portaorcamento',
            name='pintura_porta',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=5, verbose_name='Pintura da Porta'),
        ),
        migrations.AddField(
            model_name='portaorcamento',
            name='posicao_eixo',
            field=models.CharField(choices=[('Escondido', 'Escondido'), ('Aparente', 'Aparente')], default='Escondido', max_length=10),
        ),
        migrations.AddField(
            model_name='portaorcamento',
            name='possui_passagem_pedestre',
            field=models.BooleanField(default=False, verbose_name='Tem Passagem Pedestre?'),
        ),
        migrations.AddField(
            model_name='portaorcamento',
            name='qtd_pares_trava',
            field=models.PositiveIntegerField(default=0, help_text='Calculado automaticamente: qtd_lam / 2'),
        ),
        migrations.AddField(
            model_name='portaorcamento',
            name='testeira',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Altura da testeira em cm', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='portaorcamento',
            name='tp_acionamento',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Elétrico', 'Elétrico'), ('Elétrico c/ Botoeira', 'Elétrico c/ Botoeira'), ('Automático', 'Automático')], default='Manual', max_length=25, verbose_name='Tipo de Acionamento'),
        ),
        migrations.AddField(
            model_name='portaorcamento',
            name='tp_instalacao',
            field=models.CharField(choices=[('Atrás do Vão', 'Atrás do Vão'), ('Dentro do Vão', 'Dentro do Vão'), ('Fora do Vão', 'Fora do Vão')], default='Atrás do Vão', max_length=20),
        ),
        migrations.AddField(
            model_name='portaorcamento',
            name='tp_mola',
            field=models.CharField(choices=[('Sem Mola', 'Sem Mola'), ('Mola Simples', 'Mola Simples'), ('Mola Dupla', 'Mola Dupla')], default='Sem Mola', max_length=25, verbose_name='Tipo de Mola'),
        ),
        migrations.AddField(
            model_name='portaorcamento',
            name='tp_travamento',
            field=models.CharField(choices=[('Sem Trava', 'Sem Trava'), ('Trava Manual', 'Trava Manual'), ('Trava Elétrica', 'Trava Elétrica')], default='Sem Trava', max_length=25, verbose_name='Tipo de Travamento'),
        ),
        migrations.AddField(
            model_name='portaproduto',
            name='tamanho_corte',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Comprimento de corte do material em metros', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='cor',
            field=models.CharField(choices=[('', ''), ('Preto', 'Preto'), ('Branco', 'Branco'), ('Amarelo', 'Amarelo'), ('Vermelho', 'Vermelho'), ('Roxo Açaí', 'Roxo Açaí'), ('Azul Pepsi', 'Azul Pepsi'), ('Azul Claro', 'Azul Claro'), ('Cinza Claro', 'Cinza Claro'), ('Cinza Grafite', 'Cinza Grafite'), ('Cinza Chumbo', 'Cinza Chumbo'), ('Chumbo', 'Chumbo'), ('Verde', 'Verde'), ('Bege', 'Bege'), ('Bege Areia', 'Bege Areia'), ('Marrom', 'Marrom'), ('Marrom Café', 'Marrom Café'), ('Laranja', 'Laranja'), ('Azul Royal', 'Azul Royal'), ('Azul Marinho', 'Azul Marinho'), ('Verde Musgo', 'Verde Musgo'), ('Verde Bandeira', 'Verde Bandeira'), ('Vinho', 'Vinho'), ('Prata', 'Prata')], default='Preto', max_length=30),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='dt_emi',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Dt. Emissão'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='dt_ent',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Dt. Entrega'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='dt_fat',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Dt. Fatura'),
        ),
    ]
