# Generated by Django 4.1.13 on 2026-07-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_orcamento_dt_prev_instalacao_orcamento_prioridade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaorcamento',
            name='tp_lamina',
            field=models.CharField(choices=[('FECHADA_24', 'Lisa Fechada - Chapa 24 (0.65mm)'), ('FECHADA_22', 'Lisa Fechada - Chapa 22 (0.80mm)'), ('FECHADA_20', 'Lisa Fechada - Chapa 20 (0.95mm)'), ('TRANSVISION_24', 'Transvision - Chapa 24 (0.65mm)'), ('TRANSVISION_22', 'Transvision - Chapa 22 (0.80mm)'), ('TRANSVISION_20', 'Transvision - Chapa 20 (0.95mm)'), ('MISTA', 'Porta Mista (Fechada + Transvision)')], default='FECHADA_22', max_length=30),
        ),
    ]
