# Generated by Django 4.1.13 on 2025-09-27 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orcamentos", "0002_orcamento_vinc_emp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orcamento",
            options={
                "permissions": [
                    ("faturar_orcamento", "Pode faturar orçamento"),
                    ("cancelar_orcamento", "Pode cancelar orçamento"),
                    ("atribuir_desconto", "Pode atribuir desconto em orçamentos"),
                    ("atribuir_acrescimo", "Pode atribuir acréscimo em orçamentos"),
                ],
                "verbose_name_plural": "Orçamentos",
            },
        ),
    ]
