# Generated by Django 4.1.13 on 2026-07-28 00:41

from django.db import migrations, models
import django.db.models.deletion
import orcamentos.models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0003_alter_portaorcamento_tp_lamina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portaorcamento',
            name='foto_vao',
        ),
        migrations.CreateModel(
            name='PortaOrcamentoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=orcamentos.models.caminho_foto_vao_orcamento)),
                ('principal', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('porta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='orcamentos.portaorcamento')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
