# Generated by Django 4.1.13 on 2025-09-28 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("formas_pgto", "0001_initial"),
        ("produtos", "0003_alter_produto_options"),
        ("orcamentos", "0004_solicitacaopermissao"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orcamento",
            options={
                "permissions": [
                    ("faturar_orcamento", "Pode faturar orçamento"),
                    ("cancelar_orcamento", "Pode cancelar orçamento"),
                ],
                "verbose_name_plural": "Orçamentos",
            },
        ),
        migrations.RemoveField(
            model_name="orcamento",
            name="adicionais",
        ),
        migrations.RemoveField(
            model_name="orcamento",
            name="alt",
        ),
        migrations.RemoveField(
            model_name="orcamento",
            name="alt_corte",
        ),
        migrations.RemoveField(
            model_name="orcamento",
            name="cor",
        ),
        migrations.RemoveField(
            model_name="orcamento",
            name="eixo_motor",
        ),
        migrations.RemoveField(
            model_name="orcamento",
            name="fator_peso",
        ),
        migrations.RemoveField(
            model_name="orcamento",
            name="formas_pgto",
        ),
        migrations.RemoveField(
            model_name="orcamento",
            name="larg",
        ),
        migrations.RemoveField(
            model_name="orcamento",
            name="larg_corte",
        ),
        migrations.RemoveField(
            model_name="orcamento",
            name="m2",
        ),
        migrations.RemoveField(
            model_name="orcamento",
            name="obs_form_pgto",
        ),
        migrations.RemoveField(
            model_name="orcamento",
            name="peso",
        ),
        migrations.RemoveField(
            model_name="orcamento",
            name="pintura",
        ),
        migrations.RemoveField(
            model_name="orcamento",
            name="produtos",
        ),
        migrations.RemoveField(
            model_name="orcamento",
            name="qtd",
        ),
        migrations.RemoveField(
            model_name="orcamento",
            name="rolo",
        ),
        migrations.RemoveField(
            model_name="orcamento",
            name="subtotal",
        ),
        migrations.RemoveField(
            model_name="orcamento",
            name="tp_lamina",
        ),
        migrations.RemoveField(
            model_name="orcamento",
            name="tp_vao",
        ),
        migrations.AlterField(
            model_name="orcamento",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name="OrcamentoProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "orcamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produtos",
                        to="orcamentos.orcamento",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orcamentos",
                        to="produtos.produto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrcamentoFormaPgto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "forma_pgto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usos",
                        to="formas_pgto.formapgto",
                    ),
                ),
                (
                    "orcamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formas_pgto",
                        to="orcamentos.orcamento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrcamentoAdicional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "orcamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adicionais",
                        to="orcamentos.orcamento",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orcamentos_adicionais",
                        to="produtos.produto",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="orcamentoformapgto",
            constraint=models.UniqueConstraint(
                fields=("orcamento", "forma_pgto"), name="uniq_orc_formapgto"
            ),
        ),
    ]
