# Generated by Django 4.1.13 on 2026-08-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0004_remove_portaorcamento_foto_vao_portaorcamentofoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='ocasiao',
            field=models.CharField(blank=True, choices=[('Aguardando Aprovação', 'Aguardando Aprovação'), ('Aprovado', 'Aprovado'), ('Em Revisão', 'Em Revisão'), ('Recusado', 'Recusado')], db_index=True, default='Aguardando Aprovação', max_length=25, verbose_name='Ocasião'),
        ),
    ]
