# Generated by Django 4.1.13 on 2025-09-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orcamentos",
            "0005_alter_orcamento_options_remove_orcamento_adicionais_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="orcamentoformapgto",
            name="uniq_orc_formapgto",
        ),
        migrations.RenameField(
            model_name="orcamentoformapgto",
            old_name="forma_pgto",
            new_name="formas_pgto",
        ),
        migrations.AddField(
            model_name="orcamento",
            name="alt",
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name="orcamento",
            name="alt_corte",
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name="orcamento",
            name="cor",
            field=models.CharField(
                choices=[
                    ("Preto", "Preto"),
                    ("Branco", "Branco"),
                    ("Amarelo", "Amarelo"),
                    ("Vermelho", "Vermelho"),
                    ("Roxo Açaí", "Roxo Açaí"),
                    ("Azul Pepsi", "Azul Pepsi"),
                    ("Azul Claro", "Azul Claro"),
                    ("Cinza Claro", "Cinza Claro"),
                    ("Cinza Grafite", "Cinza Grafite"),
                    ("Verde", "Verde"),
                ],
                default="Preto",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="orcamento",
            name="eixo_motor",
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name="orcamento",
            name="fator_peso",
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name="orcamento",
            name="larg",
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name="orcamento",
            name="larg_corte",
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name="orcamento",
            name="m2",
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name="orcamento",
            name="obs_form_pgto",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="orcamento",
            name="peso",
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name="orcamento",
            name="pintura",
            field=models.CharField(
                choices=[("Sim", "Sim"), ("Não", "Não")], default="Sim", max_length=5
            ),
        ),
        migrations.AddField(
            model_name="orcamento",
            name="qtd",
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name="orcamento",
            name="rolo",
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name="orcamento",
            name="tp_lamina",
            field=models.CharField(
                choices=[("Fechada", "Fechada"), ("Transvision", "Transvision")],
                default="Fechada",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="orcamento",
            name="tp_vao",
            field=models.CharField(
                choices=[
                    ("Dentro do Vão", "Dentro do Vão"),
                    ("Fora do Vão", "Fora do Vão"),
                ],
                default="Fora do Vão",
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="orcamentoformapgto",
            constraint=models.UniqueConstraint(
                fields=("orcamento", "formas_pgto"), name="uniq_orc_formapgto"
            ),
        ),
    ]
