# Generated by Django 4.1.13 on 2026-08-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0005_orcamento_ocasiao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='ocasiao',
            field=models.CharField(blank=True, choices=[('Aguardando Aprovação', 'Aguardando Aprovação'), ('Em Análise', 'Em Análise'), ('Aprovado', 'Aprovado'), ('Recusado', 'Recusado')], db_index=True, default='Aguardando Aprovação', max_length=25, verbose_name='Ocasião'),
        ),
    ]
