# Generated by Django 4.1.13 on 2025-10-01 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orcamentos", "0006_remove_orcamentoformapgto_uniq_orc_formapgto_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orcamento",
            options={
                "permissions": [
                    ("clonar_orcamento", "Pode clonar orçamento"),
                    ("faturar_orcamento", "Pode faturar orçamento"),
                    ("cancelar_orcamento", "Pode cancelar orçamento"),
                    ("atribuir_desconto", "Pode atribuir descontos em orçamento"),
                    ("atribuir_acrescimo", "Pode atribuir acréscimo em orçamento"),
                ],
                "verbose_name_plural": "Orçamentos",
            },
        ),
    ]
