# Generated by Django 4.1.13 on 2026-08-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0006_alter_orcamento_ocasiao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaorcamento',
            name='garantia_motor_meses',
            field=models.PositiveIntegerField(blank=True, default=12, null=True),
        ),
    ]
