# Generated by Django 4.1.13 on 2025-10-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orcamentos", "0007_alter_orcamento_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="orcamento",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
