# Generated by Django 4.1.13 on 2025-10-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orcamentos", "0008_orcamento_subtotal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orcamento",
            name="dt_emi",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orcamento",
            name="dt_ent",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
