# Generated by Django 4.1.13 on 2025-11-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orcamentos", "0009_alter_orcamento_dt_emi_alter_orcamento_dt_ent"),
    ]

    operations = [
        migrations.AddField(
            model_name="orcamento",
            name="tp_pintura",
            field=models.CharField(
                choices=[
                    ("Eletrostática", "Eletrostática"),
                    ("Automotiva", "Automotiva"),
                ],
                default="Eletrostática",
                max_length=13,
            ),
        ),
    ]
