# Generated by Django 4.1.13 on 2025-11-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orcamentos", "0011_alter_orcamento_cor"),
    ]

    operations = [
        migrations.AddField(
            model_name="orcamento",
            name="dt_fat",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
