# Generated by Django 4.1.13 on 2025-11-23 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0004_alter_empresa_principal"),
        ("orcamentos", "0012_orcamento_dt_fat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orcamento",
            name="vinc_emp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="empresas.empresa"
            ),
        ),
    ]
