# Generated by Django 4.1.13 on 2025-11-23 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("filiais", "0007_rename_filial_usuario_filial_user"),
        ("orcamentos", "0013_alter_orcamento_vinc_emp"),
    ]

    operations = [
        migrations.AddField(
            model_name="orcamento",
            name="vinc_fil",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="filiais.filial",
            ),
            preserve_default=False,
        ),
    ]
