# Generated by Django 4.1.13 on 2025-11-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orcamentos", "0014_orcamento_vinc_fil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orcamento",
            name="dt_emi",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="orcamento",
            name="dt_ent",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="orcamento",
            name="dt_fat",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="orcamento",
            name="num_orcamento",
            field=models.CharField(db_index=True, max_length=25),
        ),
        migrations.AlterField(
            model_name="orcamento",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("Aberto", "Aberto"),
                    ("Faturado", "Faturado"),
                    ("Cancelado", "Cancelado"),
                ],
                db_index=True,
                default="Aberto",
                max_length=10,
            ),
        ),
    ]
