# Generated by Django 4.1.13 on 2025-11-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orcamentos", "0015_alter_orcamento_dt_emi_alter_orcamento_dt_ent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orcamento",
            name="qtd_lam",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="orcamento",
            name="tp_vao",
            field=models.CharField(
                choices=[
                    ("Dentro do Vão", "Dentro do Vão"),
                    ("Fora do Vão", "Fora do Vão"),
                    ("1 Lado Dentro do Vão", "1 Lado Dentro do Vão"),
                ],
                default="Fora do Vão",
                max_length=50,
            ),
        ),
    ]
