# Generated by Django 4.1.13 on 2025-11-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orcamentos", "0016_orcamento_qtd_lam_alter_orcamento_tp_vao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orcamento",
            name="qtd_lam",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
