# Generated by Django 4.1.13 on 2025-11-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orcamentos", "0017_alter_orcamento_qtd_lam"),
    ]

    operations = [
        migrations.AddField(
            model_name="orcamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("Em Produção", "Em Produção"),
                    ("Embalada", "Embalada"),
                    ("Entregue", "Entregue"),
                    ("Instalada", "Instalada"),
                ],
                db_index=True,
                default="Em Produção",
                max_length=15,
            ),
        ),
    ]
