# Generated by Django 4.2.27 on 2025-12-08 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_alter_produto_vinc_emp'),
        ('orcamentos', '0018_orcamento_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortaAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PortaOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1)),
                ('largura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qtd_lam', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('m2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('larg_corte', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('alt_corte', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rolo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('peso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fator_peso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('eixo_motor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tp_lamina', models.CharField(choices=[('Fechada', 'Fechada'), ('Transvision', 'Transvision')], default='Fechada', max_length=25)),
                ('tp_vao', models.CharField(choices=[('Dentro do Vão', 'Dentro do Vão'), ('Fora do Vão', 'Fora do Vão'), ('1 Lado Dentro do Vão', '1 Lado Dentro do Vão')], default='Fora do Vão', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PortaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='orcamentos.portaorcamento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portas_produtos', to='produtos.produto')),
            ],
        ),
        migrations.RemoveField(
            model_name='orcamentoproduto',
            name='orcamento',
        ),
        migrations.RemoveField(
            model_name='orcamentoproduto',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='alt_corte',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='eixo_motor',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='fator_peso',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='larg',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='larg_corte',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='m2',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='qtd',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='qtd_lam',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='rolo',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='tp_lamina',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='tp_vao',
        ),
        migrations.DeleteModel(
            name='OrcamentoAdicional',
        ),
        migrations.DeleteModel(
            name='OrcamentoProduto',
        ),
        migrations.AddField(
            model_name='portaorcamento',
            name='orcamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portas', to='orcamentos.orcamento'),
        ),
        migrations.AddField(
            model_name='portaadicional',
            name='porta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adicionais', to='orcamentos.portaorcamento'),
        ),
        migrations.AddField(
            model_name='portaadicional',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portas_adicionais', to='produtos.produto'),
        ),
    ]
