# Generated by Django 4.2.27 on 2025-12-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0019_portaadicional_portaorcamento_portaproduto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='portao_social',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=5),
        ),
    ]
