# Generated by Django 4.1.13 on 2025-12-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0020_orcamento_portao_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaorcamento',
            name='eixo_motor',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='portaorcamento',
            name='fator_peso',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='portaorcamento',
            name='peso',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
