# Generated by Django 4.1.13 on 2025-12-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0021_alter_portaorcamento_eixo_motor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='vl_p_s',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
