# Generated by Django 4.1.13 on 2026-02-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0022_orcamento_vl_p_s'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaproduto',
            name='regra_origem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
