# Generated by Django 4.1.13 on 2026-02-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orcamentos", "0023_portaproduto_regra_origem"),
    ]

    operations = [
        migrations.AddField(
            model_name="portaadicional",
            name="regra_origem",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="portaadicional",
            name="valor_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="portaadicional",
            name="valor_unitario",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="portaproduto",
            name="valor_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="portaproduto",
            name="valor_unitario",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
