# Generated by Django 4.1.13 on 2026-02-21 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tabelas_preco", "0003_alter_tabelapreco_vinc_emp"),
        ("orcamentos", "0024_portaadicional_regra_origem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orcamento",
            name="tabela_preco",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tabelas_preco.tabelapreco",
            ),
        ),
    ]
