# Generated by Django 4.1.13 on 2026-02-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orcamentos", "0025_orcamento_tabela_preco"),
    ]

    operations = [
        migrations.AddField(
            model_name="orcamentoformapgto",
            name="dias_intervalo",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orcamentoformapgto",
            name="parcelas",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
