# Generated by Django 4.1.13 on 2026-02-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orcamentos", "0026_orcamentoformapgto_dias_intervalo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portaorcamento",
            name="op_guia_d",
            field=models.CharField(
                choices=[
                    ("Dentro do Vão", "Dentro do Vão"),
                    ("Fora do Vão", "Fora do Vão"),
                ],
                default="Dentro do Vão",
                max_length=13,
                verbose_name="Opção Guia Direito",
            ),
        ),
        migrations.AddField(
            model_name="portaorcamento",
            name="op_guia_e",
            field=models.CharField(
                choices=[
                    ("Dentro do Vão", "Dentro do Vão"),
                    ("Fora do Vão", "Fora do Vão"),
                ],
                default="Dentro do Vão",
                max_length=13,
                verbose_name="Opção Guia Esquerdo",
            ),
        ),
    ]
