# Generated by Django 4.1.13 on 2026-03-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orcamentos", "0027_portaorcamento_op_guia_d_portaorcamento_op_guia_e"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orcamento",
            name="vl_p_s",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
