# Generated by Django 4.1.13 on 2026-03-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orcamentos", "0028_alter_orcamento_vl_p_s"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orcamento",
            options={
                "permissions": [
                    ("clonar_orcamento", "Pode clonar orçamento"),
                    ("faturar_orcamento", "Pode faturar orçamento"),
                    ("cancelar_orcamento", "Pode cancelar orçamento"),
                    ("atribuir_desconto", "Pode atribuir descontos em orçamento"),
                    ("atribuir_acrescimo", "Pode atribuir acréscimo em orçamento"),
                    (
                        "alterar_dt_venc_orc",
                        "Pode alterar a data de vencimento na fatura de orçamento",
                    ),
                ],
                "verbose_name_plural": "Orçamentos",
            },
        ),
    ]
