# Generated by Django 4.1.13 on 2026-03-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orcamentos", "0030_alter_orcamento_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="portaadicional",
            name="lado",
            field=models.CharField(
                blank=True,
                choices=[("", "---------"), ("E", "Esquerdo"), ("D", "Direito")],
                default="",
                max_length=1,
            ),
        ),
    ]
