# Generated by Django 4.1.13 on 2026-03-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orcamentos", "0031_portaadicional_lado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portaadicional",
            name="lado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "---------"),
                    ("E", "Esquerdo"),
                    ("D", "Direito"),
                    ("C", "Centro"),
                ],
                default="",
                max_length=1,
            ),
        ),
    ]
