# Generated by Django 4.1.13 on 2026-03-18 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("filiais", "0012_alter_filial_banco_fil_alter_filial_dt_criacao_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tecnicos", "0003_alter_tecnico_vinc_emp"),
        ("clientes", "0004_alter_cliente_dt_reg_and_more"),
        ("orcamentos", "0032_alter_portaadicional_lado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orcamento",
            name="cli",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="clientes.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="orcamento",
            name="solicitante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tecnicos.tecnico",
            ),
        ),
        migrations.AlterField(
            model_name="orcamento",
            name="vinc_fil",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="filiais.filial",
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaopermissao",
            name="autorizado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solicitacoes_autorizadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaopermissao",
            name="solicitante",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solicitacoes_criadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
