# Generated by Django 4.1.13 on 2026-03-20 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0009_empresa_senha_portal"),
        ("orcamentos", "0033_alter_orcamento_cli_alter_orcamento_solicitante_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaopermissao",
            name="vinc_emp",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solicitacoes_permissao",
                to="empresas.empresa",
            ),
            preserve_default=False,
        ),
    ]
