# Generated by Django 4.1.13 on 2026-03-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orcamentos", "0034_solicitacaopermissao_vinc_emp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orcamento",
            name="cor",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("Preto", "Preto"),
                    ("Branco", "Branco"),
                    ("Amarelo", "Amarelo"),
                    ("Vermelho", "Vermelho"),
                    ("Roxo Açaí", "Roxo Açaí"),
                    ("Azul Pepsi", "Azul Pepsi"),
                    ("Azul Claro", "Azul Claro"),
                    ("Cinza Claro", "Cinza Claro"),
                    ("Cinza Grafite", "Cinza Grafite"),
                    ("Cinza Chumbo", "Cinza Chumbo"),
                    ("Chumbo", "Chumbo"),
                    ("Verde", "Verde"),
                    ("Bege", "Bege"),
                    ("Bege Areia", "Bege Areia"),
                    ("Marrom", "Marrom"),
                    ("Marrom Café", "Marrom Café"),
                    ("Laranja", "Laranja"),
                    ("Azul Royal", "Azul Royal"),
                    ("Azul Marinho", "Azul Marinho"),
                    ("Azul Pepsi", "Azul Pepsi"),
                    ("Verde Musgo", "Verde Musgo"),
                    ("Verde Bandeira", "Verde Bandeira"),
                    ("Vinho", "Vinho"),
                    ("Prata", "Prata"),
                ],
                default="Preto",
                max_length=30,
            ),
        ),
    ]
