# Generated by Django 4.1.13 on 2026-04-11 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0004_alter_fornecedor_dt_reg'),
        ('orcamentos', '0035_alter_orcamento_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.fornecedor'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='nome_fornecedor',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
