# Generated by Django 4.1.13 on 2026-04-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orcamentos", "0036_orcamento_fornecedor_orcamento_nome_fornecedor"),
    ]

    operations = [
        migrations.AddField(
            model_name="orcamento",
            name="status_pagamento",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Parcial", "Parcial"),
                    ("Pago", "Pago"),
                ],
                db_index=True,
                default="Pendente",
                max_length=15,
            ),
        ),
    ]
