# Generated by Django 4.1.13 on 2026-05-12 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0037_orcamento_status_pagamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orcamento',
            options={'permissions': [('clonar_orcamento', 'Pode clonar orçamento'), ('faturar_orcamento', 'Pode faturar orçamento'), ('cancelar_orcamento', 'Pode cancelar orçamento'), ('atribuir_desconto', 'Pode atribuir descontos em orçamento'), ('atribuir_acrescimo', 'Pode atribuir acréscimo em orçamento'), ('alterar_dt_venc_orc', 'Pode alterar a data de vencimento na fatura de orçamento'), ('alterar_dt_fat_orc', 'Pode alterar a data de faturamento na fatura de orçamento'), ('vender_sem_estoque_orc', 'Pode vender sem estoque em orçamentos')], 'verbose_name_plural': 'Orçamentos'},
        ),
    ]
