# Generated by Django 4.1.13 on 2026-05-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orcamentos", "0040_orcamento_unique_codigo_orcamento_empresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaopermissao",
            name="codigo",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
