# Generated by Django 4.1.13 on 2026-07-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orcamentos", "0041_solicitacaopermissao_codigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="orcamento",
            name="at_ps",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="orcamento",
            name="lg_ps",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
