# Generated by Django 4.1.13 on 2026-07-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(choices=[('Ativa', 'Ativa'), ('Inativa', 'Inativa')], max_length=10, verbose_name='Situação')),
                ('principal', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=10, verbose_name='Principal?')),
                ('senha_portal', models.CharField(default='0000', max_length=128)),
                ('cnpj', models.CharField(max_length=20, verbose_name='CNPJ')),
                ('ie', models.CharField(max_length=20, verbose_name='IE')),
                ('razao_social', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('fantasia', models.CharField(max_length=100, verbose_name='Fantasia')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('numero', models.CharField(max_length=10, verbose_name='Nº')),
                ('bairro_emp', models.CharField(max_length=20, verbose_name='Bairro')),
                ('complem', models.CharField(blank=True, max_length=20, verbose_name='Complemento')),
                ('cidade_emp', models.CharField(max_length=30, verbose_name='Cidade')),
                ('uf_emp', models.CharField(max_length=2, verbose_name='UF')),
                ('tel', models.CharField(max_length=15, verbose_name='Fone')),
                ('email', models.EmailField(max_length=40, verbose_name='E-mail')),
                ('fantasia_normalizado', models.CharField(editable=False, max_length=255)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Responsável')),
                ('cpf', models.CharField(max_length=15, verbose_name='CPF')),
                ('orgao', models.CharField(max_length=30, verbose_name='Órgão Emissor')),
                ('dt_nasc', models.CharField(max_length=20, verbose_name='Data de Nascimento')),
                ('endereco_adm', models.CharField(max_length=100, verbose_name='Endereço')),
                ('cep_adm', models.CharField(max_length=10, verbose_name='CEP')),
                ('numero_adm', models.CharField(max_length=10, verbose_name='Nº')),
                ('bairro_adm', models.CharField(max_length=20, verbose_name='Bairro')),
                ('cidade_adm', models.CharField(max_length=30, verbose_name='Cidade')),
                ('uf_adm', models.CharField(max_length=2, verbose_name='UF')),
                ('tel_adm', models.CharField(max_length=15, verbose_name='Fone')),
                ('email_adm', models.EmailField(max_length=40, verbose_name='E-mail')),
                ('logo', models.FileField(blank=True, default='default_logo.png', null=True, upload_to='logo/')),
                ('dia_venc', models.CharField(choices=[('05', '05'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30')], default='05', max_length=10)),
                ('dt_criacao', models.DateField(auto_now_add=True, verbose_name='Data de Registro')),
                ('dt_inativacao', models.DateField(blank=True, null=True, verbose_name='Data de Inativação')),
                ('qtd_filial', models.PositiveIntegerField(default=1, verbose_name='Quantidade de Filiais Ativas')),
                ('qtd_usuarios', models.PositiveIntegerField(default=1, verbose_name='Quantidade de Usuários Ativos')),
                ('tp_calc_juros', models.CharField(choices=[('Percentual', 'Percentual'), ('Valor', 'Valor')], default='Percentual', max_length=15, verbose_name='Tp. Cálculo Juros')),
                ('tp_calc_multa', models.CharField(choices=[('Percentual', 'Percentual'), ('Valor', 'Valor')], default='Percentual', max_length=15, verbose_name='Tp. Cálculo Multa')),
                ('ft_multa', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Fator Multa')),
                ('ft_juros', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Fator Juros')),
                ('gerar_filial', models.BooleanField(default=False, verbose_name='Gerar Filial?')),
            ],
            options={
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
