# Generated by Django 4.1.13 on 2025-09-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="qtd_filial",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Quantidade de Filiais Ativas"
            ),
        ),
    ]
