# Generated by Django 4.1.13 on 2025-11-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0002_alter_empresa_qtd_filial"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="principal",
            field=models.CharField(
                choices=[("Sim", "Sim"), ("Não", "Não")],
                default="Sim",
                max_length=10,
                verbose_name="Principal?",
            ),
            preserve_default=False,
        ),
    ]
