# Generated by Django 4.1.13 on 2025-11-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0003_empresa_principal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="principal",
            field=models.CharField(
                choices=[("Sim", "Sim"), ("Não", "Não")],
                default="Não",
                max_length=10,
                verbose_name="Principal?",
            ),
        ),
    ]
