# Generated by Django 4.1.13 on 2026-02-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0004_alter_empresa_principal"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="ft_juros",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="ft_multa",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="tp_calc_juros",
            field=models.CharField(
                choices=[("Percentual", "Percentual"), ("Valor", "Valor")],
                default="Percentual",
                max_length=15,
                verbose_name="Tp. Cálculo Júros",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="tp_calc_multa",
            field=models.CharField(
                choices=[("Percentual", "Percentual"), ("Valor", "Valor")],
                default="Percentual",
                max_length=15,
                verbose_name="Tp. Cálculo Júros",
            ),
        ),
    ]
