# Generated by Django 4.1.13 on 2026-02-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0005_empresa_ft_juros_empresa_ft_multa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="tp_calc_multa",
            field=models.CharField(
                choices=[("Percentual", "Percentual"), ("Valor", "Valor")],
                default="Percentual",
                max_length=15,
                verbose_name="Tp. Cálculo Multa",
            ),
        ),
    ]
