# Generated by Django 4.1.13 on 2026-02-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0006_alter_empresa_tp_calc_multa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="ft_juros",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Fator Juros",
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="ft_multa",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Fator Multa",
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="tp_calc_juros",
            field=models.CharField(
                choices=[("Percentual", "Percentual"), ("Valor", "Valor")],
                default="Percentual",
                max_length=15,
                verbose_name="Tp. Cálculo Juros",
            ),
        ),
    ]
