# Generated by Django 4.1.13 on 2026-02-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0007_alter_empresa_ft_juros_alter_empresa_ft_multa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="ie",
            field=models.CharField(max_length=20, verbose_name="IE"),
        ),
    ]
