# Generated by Django 4.1.13 on 2026-02-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0008_alter_empresa_ie"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="senha_portal",
            field=models.CharField(default="0000", max_length=128),
        ),
    ]
