# Generated by Django 4.1.13 on 2026-08-04 20:06

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0001_initial'),
        ('filiais', '0016_alter_usuario_tel'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(blank=True, null=True)),
                ('num_conta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Conta')),
                ('tp_juros', models.CharField(choices=[('Percentual', 'Percentual'), ('Valor', 'Valor')], default='Percentual', max_length=15, verbose_name='Tp. Cálculo Juros')),
                ('tp_multa', models.CharField(choices=[('Percentual', 'Percentual'), ('Valor', 'Valor')], default='Percentual', max_length=15, verbose_name='Tp. Cálculo Multa')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('juros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('multa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('data_emissao', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('Aberta', 'Aberta'), ('Paga', 'Paga')], default='Aberta', max_length=14)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=14)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('obs_internas', models.TextField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True, default='', null=True)),
                ('tipo', models.CharField(choices=[('Original', 'Original'), ('Remanescente', 'Remanescente')], default='Original', max_length=15)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('filial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filiais.filial')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos_fornecedores', to='fornecedores.fornecedor')),
                ('titulo_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titulos_remanescentes', to='contas_pagar.contapagar')),
            ],
            options={
                'verbose_name_plural': 'Contas à Pagar',
                'permissions': [('baixar_cp', 'Pode realizar baixa em contas à pagar'), ('estornar_cp', 'Pode realizar estorno em contas à pagar')],
            },
        ),
        migrations.AddConstraint(
            model_name='contapagar',
            constraint=models.UniqueConstraint(fields=('codigo', 'empresa'), name='unique_codigo_contas_pagar_empresa'),
        ),
    ]
