# Generated by Django 4.1.13 on 2026-08-06 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_cobranca', '0001_initial'),
        ('entradas', '0005_cobrancaentrada_tp_conta'),
        ('contas_pagar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos_entrada', to='entradas.entrada'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='tp_cobranca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipo_cobranca.tipocobranca', verbose_name='Tipo de Cobrança'),
        ),
    ]
