# Generated by Django 4.1.13 on 2025-09-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("Ativo", "Ativo"),
                            ("Baixada", "Suspenso"),
                            ("Cancelado", "Cancelado"),
                        ],
                        default="Ativo",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Pendente", "Pendente"), ("Aprovado", "Aprovado")],
                        default="Pendente",
                        max_length=10,
                    ),
                ),
                ("dt_inicio", models.DateField()),
                ("qtd_parcelas", models.IntegerField()),
                (
                    "valor_mensalidade",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("obs", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
