# Generated by Django 4.1.13 on 2026-07-15 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(choices=[('Ativo', 'Ativo'), ('Baixada', 'Suspenso'), ('Cancelado', 'Cancelado'), ('Expirado', 'Expirado')], default='Ativo', max_length=10)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado')], default='Pendente', max_length=10)),
                ('dt_inicio', models.DateField()),
                ('dt_exp', models.DateField(blank=True, null=True)),
                ('qtd_meses', models.IntegerField(default=12)),
                ('valor_mensalidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('obs', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
        ),
    ]
