# Generated by Django 4.1.13 on 2026-02-05 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0004_alter_empresa_principal"),
        ("contratos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="empresa",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="empresas.empresa",
            ),
            preserve_default=False,
        ),
    ]
