# Generated by Django 4.1.13 on 2026-02-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0002_contrato_empresa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="qtd_parcelas",
            field=models.IntegerField(default=12),
        ),
    ]
