# Generated by Django 4.1.13 on 2026-02-05 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0003_alter_contrato_qtd_parcelas"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contrato",
            old_name="qtd_parcelas",
            new_name="qtd_meses",
        ),
    ]
