# Generated by Django 4.1.13 on 2026-02-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0004_rename_qtd_parcelas_contrato_qtd_meses"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="dt_exp",
            field=models.DateField(blank=True, null=True),
        ),
    ]
