# Generated by Django 4.1.13 on 2026-02-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0005_contrato_dt_exp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("Ativo", "Ativo"),
                    ("Baixada", "Suspenso"),
                    ("Cancelado", "Cancelado"),
                    ("Expirado", "Expirado"),
                ],
                default="Ativo",
                max_length=10,
            ),
        ),
    ]
